#!/bin/sh

exec dotnet /usr/lib/emby-server/EmbyServer.dll \
  -programdata $PROGRAM_DATA \
  -ffdetect $FFDETECT \
  -ffmpeg $FFMPEG \
  -ffprobe $FFPROBE \
  -restartexitcode 3

# vim: ts=2 sw=2 et:
