post_install() {
  getent group exim >/dev/null 2>&1 || groupadd -g 79 exim 
  if getent passwd exim > /dev/null 2>&1; then
    usr/sbin/usermod -d /var/spool/exim -c 'Exim MTA' -s /sbin/nologin exim > /dev/null 2>&1
  else
    usr/sbin/useradd -c 'Exim MTA' -u 79 -g exim -d /var/spool/exim -s /sbin/nologin exim 
  fi
  passwd -l exim > /dev/null
  chmod u+s /usr/bin/exim
}

post_upgrade() {
  post_install
}
