pkgname=awn

post_install() {
  echo ""
  echo "It is safe to ignore the SCHEMA warnings below"
  echo ""

  usr/sbin/gconfpkg --install ${pkgname}
  update-desktop-database -q
  which xdg-icon-resource 1>/dev/null 2>/dev/null && xdg-icon-resource forceupdate || true
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  echo ""
  echo "It is safe to ignore the SCHEMA warnings below"
  echo ""

  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  update-desktop-database -q
  which xdg-icon-resource 1>/dev/null 2>/dev/null && xdg-icon-resource forceupdate || true
}
