post_install() {
	echo "$ sudo setcap 'cap_sys_tty_config+ep' /usr/bin/fbterm"
	echo "or"
	echo "$ sudo chmod u+s /usr/bin/fbterm"

	echo "Do above once,Then launch fbterm with fcitx"
	echo "$ fcitx-fbterm-helper -l"
}
post_upgrade() {
        echo "$ sudo setcap 'cap_sys_tty_config+ep' /usr/bin/fbterm"
	echo "or"
	echo "$ sudo chmod u+s /usr/bin/fbterm"

	echo "Do above once,Then launch fbterm with fcitx"
	echo "$ fcitx-fbterm-helper -l"
}
