infodir=usr/share/info
filelist=(gst-base.info{,-1,-2,-3,-4,-5}.gz gst-libs.info{,-1,-2,-3}.gz gst.info{,-1,-2}.gz)

post_install() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}

# vim:set ts=2 sw=2 et:
