post_install() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-mime-database usr/share/mime &>/dev/null
  update-desktop-database -q
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install
}

pre_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-mime-database usr/share/mime &>/dev/null
  update-desktop-database -q
}

# vim:set ts=2 sw=2 et:
