echo_shortcut() {
	echo "See the link about keyboard shortcuts: https://github.com/lupoDharkael/flameshot#keyboard-shortcuts"
}

echo_gnome3() {
	echo "For Gnome3 users: please install one of the tray icons extension to use the systray icon"
}

post_upgrade(){
	if [ $(vercmp $2 0.5.1) -lt 0 ]; then
        echo_shortcut
	fi

	if [ $(vercmp $2 0.5.1-3) -lt 0 ]; then
        echo_gnome3
	fi
}

post_install(){
    echo_shortcut
    echo_gnome3
}
