# Maintainer: Sergej Pupykin <pupykin.s+arch@gmail.com>
# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman
# Contributor: François Charette <firmicus ατ gmx δοτ net>

pkgname=perl-io-string
pkgver=1.08
pkgrel=12
pkgdesc="IO::File interface for in-core strings"
arch=('x86_64')
url="https://search.cpan.org/dist/IO-String"
license=('GPL' 'PerlArtistic')
depends=('perl>=5.10.0')
options=('!emptydirs')
source=(https://www.cpan.org/authors/id/G/GA/GAAS/IO-String-$pkgver.tar.gz)
sha256sums=('2a3f4ad8442d9070780e58ef43722d19d1ee21a803bf7c8206877a10482de5a0')

build() {
  cd  "$srcdir"/IO-String-$pkgver
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor
  make
}

package() {
  cd  "$srcdir"/IO-String-$pkgver
  make install DESTDIR="$pkgdir"
  find "$pkgdir" -name '.packlist' -delete
  find "$pkgdir" -name '*.pod' -delete
}
