post_upgrade() {
  if (( "$(vercmp $2 0.13.0-1)" < 0 )); then
    cat << EOF
  This is the first release on the new major v0.13 branch. It is not
  protocol compatible with the v0.12.x releases! Use this release if you are
  a new user, or when you are ready to upgrade all devices in your cluster.
  Full information is available on the release page
  https://github.com/syncthing/syncthing/releases/tag/v0.13.0

EOF
  fi
}
