infodir=usr/share/info
filelist=(avr-as.info avr-bfd.info avr-binutils.info avr-configure.info avr-gprof.info avr-ld.info avr-standards.info)

post_upgrade() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    install-info $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}

pre_remove() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}

