post_install() {
  # Make uploads work
  install -dm775 /srv/http/wordpress/wp-content/uploads
  chown http:http /srv/http/wordpress/wp-content/uploads
  echo 'You can now configure your (PHP compatible) web server to run Wordpress'
}

pre_remove() {
  cp -r /srv/http/wordpress /srv/http/wordpress_backup
  echo 'Your Wordpress folder were backed up to /srv/http/wordpress_backup'
}

post_remove() {
  rm -rf /srv/http/wordpress
}

# vim:set ts=2 sw=2 et:
