post_install() {
  echo ">> If XBMC won't start, but just segfaults, double check your X.Org config"
  echo ">> so that your display depth is at least 24-bit. Eg: change "
  echo ">> \"DefaultDepth 16\" under the \"Screen\" section so it says 24 instead"
  echo ">> of 16."
  echo " "
  echo ">> PM3.HD skin got removed"
  echo ">> xbmc basedir is now /opt/xbmc !!!"
  echo ">> keep above in mind for your skins"
  /bin/true
}
