
# arg 1:  the new package version
pre_install() {
  /bin/true
}

# arg 1:  the new package version
post_install() {
	mv /usr/lib/perl5/current/ExtUtils/xsubpp /usr/lib/perl5/current/ExtUtils/xsubpp.old
	cp /usr/lib/perl5/current/ExtUtils/xsubpp.new /usr/lib/perl5/current/ExtUtils/xsubpp
}

# arg 1:  the new package version
# arg 2:  the old package version
pre_upgrade() {
  /bin/true
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	cp /usr/lib/perl5/current/ExtUtils/xsubpp.new /usr/lib/perl5/current/ExtUtils/xsubpp
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

# arg 1:  the old package version
post_remove() {
	mv /usr/lib/perl5/current/ExtUtils/xsubpp.old /usr/lib/perl5/current/ExtUtils/xsubpp
}

