_1.03.2_14_changes() {
  echo ":: The hyperiond.service now runs as independent user 'hyperion'."
  echo "   Make sure you still have access rights to your ambilight devices."
  echo "   The user 'hyperion' belongs to the 'uucp' group."
  echo "   Also see: https://wiki.archlinux.org/index.php/users_and_groups"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
    local v upgrades=(
      1.03.2-14
    )

    for v in "${upgrades[@]}"; do
      if [[ $(vercmp "$v" "$2") -eq 1 ]]; then
        "_${v//-/_}_changes"
      fi
    done
}
