#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON=/usr/sbin/pcscd
NAME=pcscd
DESC="PC/SC smart card daemon"
PID_FILE=/run/pcscd/pcscd.pid
PCSCD_OPTIONS=

case "$1" in
    start)
        stat_busy "Starting $DESC"
        $DAEMON $PCSCD_OPTIONS
        if [ $? -gt 0 ]; then
            stat_fail
        else
            add_daemon $NAME
            stat_done
        fi
        ;;

    stop)
        stat_busy "Stopping $DESC"
        [ -f $PID_FILE ] && kill `cat $PID_FILE` &> /dev/null
        if [ $? -gt 0 ]; then
            stat_fail
        else
            rm_daemon $NAME
            stat_done
        fi
        ;;

    restart)
        $0 stop
        sleep 3
        $0 start
        ;;

    status)
        stat_busy "Checking $NAME status";
        ck_status $NAME
        ;;

    *)
        echo "usage: $0 {start|stop|restart|status}"
	;;

esac

exit 0

