#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

# source application-specific settings
[ -f /etc/conf.d/tor ] && . /etc/conf.d/tor

PID=`pidof -o %PPID /usr/bin/tor`
case "$1" in
  start)
    stat_busy "Starting Tor Daemon"
    if [ -z "${TOR_MAX_FD}" ] || ulimit -n "${TOR_MAX_FD}"; then
      [ -z "$PID" ] && /usr/bin/tor -f ${TOR_CONF} ${TOR_ARGS} &>/dev/null
      if [ $? -gt 0 ]; then
        stat_fail
      else
        add_daemon tor
        stat_done
      fi
    else
      stat_fail
    fi
    ;;
  stop)
    stat_busy "Stopping Tor Daemon"
    [ ! -z "$PID" ] && kill -INT $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon tor
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
# vim: ft=sh ts=2 sw=2
