post_install() {
   echo "See \"MythTV\" on the Archlinux Wiki for installation information - Extensive!!"
}

post_upgrade() {
   echo "Make sure you rescan for audio devices (use the frontend audio settings menu)"
   echo "See http://www.mythtv.org/wiki/Release_Notes_-_0.24 for details"
}

post_remove() {
   echo -e "NOTE: mysql database was not removed. To remove run:\nmysql -u root -e 'drop database mythconverg;'"
}
