pkgname=last-exit

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  scrollkeeper-update -q -p var/lib/scrollkeeper
  update-desktop-database -q
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  scrollkeeper-update -q -p var/lib/scrollkeeper
  update-desktop-database -q
}

# vim:set ts=2 sw=2 et:
