post_install() {
  useradd -r -s /bin/false -d /var/lib/quassel quassel
  mkdir -p /var/lib/quassel && chown -R quassel:quassel /var/lib/quassel
}

post_upgrade() {
  [ `vercmp $2 0.5.2-1` -le 0 ] && (
    cat <<EOF

==> - quasselcore now runs as the quassel user
==> - quasselcore now listens to port 127.0.0.1 by default
==> - both of above are configurable: /etc/conf.d/quassel
EOF
    post_install
  ) || true
}

post_remove() {
  userdel quassel
}
