#!/bin/bash

. /etc/rc.conf
. /etc/conf.d/mldonkey
. /etc/rc.d/functions

if [ -z $MLDUSER ] ; then
	echo "Unable to run MLDonkey. You must set a user in /etc/conf.d/mldonkey ."
	exit 2
fi

USERDIR=$(getent passwd $MLDUSER | cut -d: -f6)

if [ ! -d $USERDIR ]; then
	echo "Unable to run MLDonkey. Home directory for ${MLDUSER} does not exist."
	exit 2
fi

PID=$(cat $USERDIR/.mldonkey/mlnet.pid 2>/dev/null)

case "$1" in
    	start)
        	stat_busy "Starting MLDonkey"
		[ -z $PID ] && su $MLDUSER -s /bin/sh -c "/usr/bin/mlnet $PARAMS -log_to_syslog true &> /tmp/mldonkey.log &"
		if [ $? -gt 0 ]; then
			stat_fail
		else
			add_daemon mldonkey
			stat_done
		fi
	;;
    	stop)
        	stat_busy "Stopping MLDonkey"
		[ ! -z $PID ] && kill $PID &> /dev/null
		if [ $? -gt 0 ]; then
			stat_fail
		else
			rm_daemon mldonkey
			stat_done
		fi
	;;
    	restart)
        	$0 stop
		sleep 1
        	$0 start
        ;;
    	*)
        	echo "usage: $0 {start|stop|restart}"
esac
exit 0
