#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

rnd_device=/dev/random
rng_device=/dev/hw_random
timeout=0

[ -f /etc/conf.d/rngd ] && . /etc/conf.d/rngd
PID=$(pidof -o %PPID /usr/sbin/rngd)
case "$1" in
  start)
    stat_busy "Starting RNG"
    [ -z "$PID" ] && /usr/sbin/rngd $RNGD_OPTS
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon rngd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping RNG"
    [ ! -z "$PID" ]  && kill -s SIGALRM $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon rngd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
