post_install() {
  cat << EOF

Note: For ttf-nerd-fonts-symbols-mono, use the "Symbols Nerd Font Mono" family
in your font config.

Symlink /usr/share/fontconfig/conf.avail/10-nerd-font-symbols.conf to
/etc/fonts/conf.d/, or see \`man 5 fonts-conf\` for other options.
EOF
}

post_remove() {
  cat << EOF
Remove Symbols Nerd Font from your font configuration files, eg.
\`rm /etc/fonts/conf.d/10-nerd-font-symbols.conf\`.
EOF
}
