_depmod() {
  EXTRAMODULES=extramodules-4.5-ARCH
  depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_install() {
  cat << EOF
==> Virtualbox kernel modules will be loaded at boot time by systemd-modules-load.
==> In order to use them right now, you may want to load them manually.
==> Read modules-load.d man page to disable module boot loading.'
EOF
  _depmod
}

post_upgrade() {
  _depmod
}

post_remove() {
  _depmod
}

# vim:set ts=2 sw=2 et:
