post_install() {
	if [[ ! -e /etc/munge/munge.key && -c /dev/urandom ]]; then
		echo "Creating random munge key at /etc/munge/munge.key"
		dd if=/dev/urandom bs=1 count=1024 of=/etc/munge/munge.key
		chmod 0400 /etc/munge/munge.key
	else
		if [[ -c /dev/urandom ]]; then
			echo "No munge key generated since /etc/munge/munge.key already exists."
		else
			echo "Did not create /etc/munge/munge.key since /dev/urandom can not be found."
		fi
	fi
}
