post_upgrade() {
  cat << EOF
---[ NOTE ]--------------------------------------------------------------------
 Processing does not support OpenJDK, only Java from Oracle.
 https://github.com/processing/processing/wiki/Supported-Platforms#linux
 If you encounter issues with this package, please file pull requests for
 Processing and/or OpenJDK until Processing can officially support OpenJDK.
-------------------------------------------------------------------------------
EOF
}

post_install() {
  post_upgrade
}
