## arg 1:  the new package version

post_upgrade() {
  (( $(vercmp 1.24-3 $2) > 0 )) && cat <<EOF
ATTENTION:
  /etc/conf.d/inputattach.conf has been replaced by /etc/conf.d/inputattach
  Make sure you adjust the new config file, which has a new format.
EOF
}

post_install() {
  cat << EOF
The correct device mode and /dev device file will need to be set in
/etc/conf.d/inputattach before starting /etc/rc.d/inputattach
EOF
}
