post_install() {
  EXTRAMODULES='extramodules-3.6-ARCH'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)
  echo "==> For more information about the use and config of the drivers,"
  echo "==> have a look at http://wiki.archlinux.org/index.php/Slmodem_drivers"
}

post_upgrade() {
  EXTRAMODULES='extramodules-3.6-ARCH'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

post_remove() {
  EXTRAMODULES='extramodules-3.6-ARCH'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)
}
