post_install() {
  echo ">>> Updating module dependencies. Please wait ..."
  KERNEL_VERSION=2.6.38-ARCH
  depmod -v $KERNEL_VERSION   > /dev/null 2>&1
  echo
  echo
  echo "==> NOTICE:"
  echo "==> For more information about the use and config of the drivers,"
  echo "==> have a look at http://wiki.archlinux.org/index.php/Slmodem_drivers"
}

post_upgrade() {
  post_install
}

post_remove() {
  echo ">>> Updating module dependencies. Please wait ..."
  KERNEL_VERSION=2.6.38-ARCH
  depmod -v $KERNEL_VERSION   > /dev/null 2>&1
}
