#!/bin/bash

. /etc/rc.d/functions
. /etc/conf.d/sysstat
. /etc/rc.conf

case "$1" in
  start)
    stat_busy "Writing SysStat restart record"
    /usr/lib/sa/sadc -L -F ${SADC_OPTIONS} -
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon sysstat
      stat_done
    fi
    ;;
  stop)
    echo "Stopping SysStat is useless"
    rm_daemon sysstat
    ;;
  *)
    echo "usage: $0 {start|stop}"
esac
exit 0
