post_upgrade() {
    getent group mopidy &>/dev/null || groupadd -g 46 mopidy >/dev/null
    getent passwd mopidy &>/dev/null || useradd -u 46 -d /var/lib/mopidy -s /bin/false -g mopidy -G audio mopidy >/dev/null

    # Remove me when updating to pkgrel -5 or a new pkgver
    echo "It's adviced to change the ownership of /var/lib/mopidy to mopidy:mopidy."
    echo "Otherwise some mopidy addons might not work."
}

post_install() {
    post_upgrade
}
