# https://wiki.archlinux.org/index.php/UID_and_GID_List
# 0:15 = root:proxy

post_install() {
  getent group proxy >/dev/null || groupadd -r -g 15 proxy
  getent passwd proxy >/dev/null || useradd -r -d /var/empty -g 15 -u 15 proxy
  mkdir -p /var/log/ziproxy && \
  chown -R 0:15 /var/log/ziproxy && \
  chmod -R ug+w /var/log/ziproxy
}

post_upgrade() {
  mkdir -p /var/log/ziproxy && \
  chown -R 0:15 /var/log/ziproxy && \
  chmod -R ug+w /var/log/ziproxy
}
