post_upgrade() {
  if [ "$(vercmp "$2" '1.9.5-1')" -le 0 ]; then
    echo 'The configuration file(s) and setup of dnscrypt-proxy has changed considerably since version 1.x.'
    echo 'Please refer to the new upstream information for help!'
  fi
  if [ "$(vercmp "$2" '2.0.45-1')" -le 0 ]; then
    echo 'Some of the configuration files have been renamed. Read /usr/share/doc/dnscrypt-proxy/ChangeLog to merge files accordingly.'
  fi
}
