#!/bin/bash

# source application-specific settings
[ -f /etc/conf.d/tenshi ] && . /etc/conf.d/tenshi

. /etc/rc.conf
. /etc/rc.d/functions

PID=`cat $TENSHI_PID 2>/dev/null`

start() {
  stat_busy "Starting Tenshi log monitor"
  [ -z "$PID" ] && /usr/sbin/tenshi $TENSHI_OPTIONS
  if [ $? -gt 0 ]; then
    stat_fail
  else
    add_daemon tenshi
    stat_done
  fi
}

stop() {
  stat_busy "Stopping Tenshi log monitor"
  [ ! -z "$PID" ]  && kill $PID
  if [ $? -gt 0 ]; then
    stat_fail
  else
    rm -f $TENSHI_PID
    rm_daemon tenshi
    stat_done
  fi
}

reload() {
  stat_busy "Reloading Tenshi log monitor"
  [ ! -z "$PID" ] && kill -HUP $PID
  if [ $? -gt 0 ]; then
    stat_fail
  else
    stat_done
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    # calling 'stop' and 'start' without the $0 fails...
    $0 stop
    $0 start
    ;;
  reload)
    reload
    ;;
  *)
    echo "usage: $0 {start|stop|restart|reload}"
esac
exit 0
