#!/bin/sh

## arg 1:  the new package version
post_install() {
  type systemd-tmpfiles >/dev/null && systemd-tmpfiles --create picocom.conf
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install "$1"
}

## arg 1:  the old package version
post_remove() {
 type systemd-tmpfiles >/dev/null && systemd-tmpfiles --clean --remove picocom.conf
}

# vim:set ts=2 sw=2 ft=sh et:
