# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  if [ "$(vercmp $2 2:r10820.4e81233ac-1)" -le 0 ]; then
    cat << EOF
===> tt-rss switched back to PHP 8.
===> Please reconfigure PHP-specific bits:
===>   * Enable required modules in /etc/php/php.ini
===>   * Start/enable php-fpm systemd service
===> See https://wiki.archlinux.org/index.php/TT-RSS for more information.
===> ********************************************************************
===> TT-RSS has restructured its config files, please consult
===>   https://tt-rss.org/wiki/GlobalConfig
===> on the config file migration plan.
EOF
  fi
}
