post_install() {
  echo
  echo -n "==> Updating desktop database..."
  gtk-update-icon-cache --quiet /usr/share/icons/hicolor
  update-mime-database /usr/share/mime &> /dev/null
  echo "done."
  echo
  echo "==> You have to install at least one of the"
  echo "==> UI packages from the optdepends list."
  echo
}

post_remove() {
  gtk-update-icon-cache --quiet /usr/share/icons/hicolor
  update-mime-database /usr/share/mime &> /dev/null
}
