post_install() {
  glib-compile-schemas usr/share/glib-2.0/schemas
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
  post_install $1

  if [ "$(vercmp 0.2.4.1-3 "$2")" -eq 1 ]; then
    printf '==> Users have to fix/delete their profiles in ~/.local/share/gnac/profiles\n'
    printf '    after upgrade to make them compatible with GStreamer 1.0.\n'
  fi
}

post_remove() {
  post_install $1
}
