# Look for the header file.
FIND_PATH(HTTP_PARSER_INCLUDE_DIR NAMES http_parser.h)

# Look for the library.
FIND_LIBRARY(HTTP_PARSER_LIBRARY NAMES http_parser)

# Handle the QUIETLY and REQUIRED arguments and set HTTP_PARSER_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HTTP_Parser DEFAULT_MSG HTTP_PARSER_LIBRARY HTTP_PARSER_INCLUDE_DIR)

# Copy the results to the output variables.
IF(HTTP_PARSER_FOUND)
    SET(HTTP_PARSER_LIBRARIES ${HTTP_PARSER_LIBRARY})
    SET(HTTP_PARSER_INCLUDE_DIRS ${HTTP_PARSER_INCLUDE_DIR})
ELSE(HTTP_PARSER_FOUND)
    SET(HTTP_PARSER_LIBRARIES)
    SET(HTTP_PARSER_INCLUDE_DIRS)
ENDIF(HTTP_PARSER_FOUND)

MARK_AS_ADVANCED(HTTP_PARSER_INCLUDE_DIRS HTTP_PARSER_LIBRARIES)
