post_install() {
  getent passwd haproxy >/dev/null || useradd -r -M -d / \
    -s /usr/bin/nologin haproxy >/dev/null

  printf '==> %s\n' "The example config chroots HAProxy, meaning that logging to journald won't work."
  printf '    %s\n' "Either disable chrooting, use rsyslog, or bind /run/systemd/journal/dev-log into the chroot."
}

post_upgrade() {
  printf '==> %s\n' "The example config chroots HAProxy, meaning that logging to journald won't work."
  printf '    %s\n' "Either disable chrooting, use rsyslog, or bind /run/systemd/journal/dev-log into the chroot."
}
