create_polipo_user() {
  getent group polipo &>/dev/null || groupadd -g 185 polipo >/dev/null
  getent passwd polipo &>/dev/null || useradd -u 185 -g polipo \
                                              -d /var/cache/polipo \
                                              -c 'Caching web proxy' \
                                              -s /bin/nologin polipo >/dev/null
}

post_install() {
  post_upgrade $1 ''
}

post_upgrade() {
  create_polipo_user
}

# vim:set ts=2 sw=2 et:
