post_install() {
  getent passwd gnome-initial-setup > /dev/null 2>&1 && \
    usermod -c 'GNOME Initial Setup' -d /var/lib/gnome-initial-setup -s /sbin/nologin gnome-initial-setup > /dev/null 2>&1 || \
    useradd -rM -c 'GNOME Initial Setup' -d /var/lib/gnome-initial-setup -s /sbin/nologin gnome-initial-setup
  passwd -l gnome-initial-setup > /dev/null
}

post_upgrade() {
  post_install
}

post_remove() {
  getent passwd gnome-initial-setup > /dev/null 2>&1 && userdel gnome-initial-setup
}
