# custom variables
pkgname=haskell-haddock-api
HS_DIR=usr/share/haskell/${pkgname}

# functions
post_install() {
    ${HS_DIR}/register.sh
    /usr/share/doc/ghc/html/libraries/arch-gen-contents-index
}

pre_upgrade() {
    ${HS_DIR}/unregister.sh
}

post_upgrade() {
    ${HS_DIR}/register.sh
    /usr/share/doc/ghc/html/libraries/arch-gen-contents-index
}

pre_remove() {
    ${HS_DIR}/unregister.sh
}

post_remove() {
    /usr/share/doc/ghc/html/libraries/arch-gen-contents-index
}
