# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman
# Contributor: François Charette <firmicus ατ gmx δοτ net>

pkgname=perl-datetime-format-mail
pkgver=0.403
pkgrel=4
pkgdesc="Convert between DateTime and RFC2822/822 formats "
arch=('x86_64')
url="https://search.cpan.org/dist/DateTime-Format-Mail"
license=('GPL' 'PerlArtistic')
depends=('perl>=5.10.0' 'perl-datetime' 'perl-params-validate>=0.67')
options=('!emptydirs')
source=("https://search.cpan.org/CPAN/authors/id/B/BO/BOOK/DateTime-Format-Mail-$pkgver.tar.gz")
md5sums=('b34a52d96290c42cf53e8db0a8f16ecd')

build() {
  cd  "$srcdir"/DateTime-Format-Mail-$pkgver
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor 
  make
}
package() {
  cd  "$srcdir"/DateTime-Format-Mail-$pkgver
  make install DESTDIR="$pkgdir"
  find "$pkgdir" -name '.packlist' -delete
  find "$pkgdir" -name '*.pod' -delete
}
