post_install() {
    if [ -z "`grep '^postgrey::' /etc/group`" ]; then
        groupadd -r postgrey >& /dev/null
    fi
    if [ -z "`grep '^postgrey:' /etc/passwd`" ]; then
        useradd -r -d /var/spool/postfix/postgrey -g postgrey -s /bin/false postgrey
    fi

    mkdir -p var/run/postgrey
    chown postgrey:postgrey /var/spool/postfix/postgrey
    chown postgrey:postgrey var/run/postgrey
}

post_upgrade() {
    post_install $1
}
