post_upgrade() {
  local new_package_version="$1"
  local old_package_version="$2"
  if [ $(vercmp "${old_package_version}" "3.2.0") -le 0 ]; then
cat <<EOF
The webapp now needs to be run as its own user/group: postfixadmin/postfixadmin.
The webapp is now installed to /usr/share/webapps/postfixadmin.
It's encouraged to move configuration to config.local.php as the default
configuration in config.inc.php will not be backed up anymore in a future
release.
EOF
  fi
}
