#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

# source application-specific settings
[ -f /etc/conf.d/privoxy ] && . /etc/conf.d/privoxy

PID=`pidof -o %PPID /usr/sbin/privoxy`

case "$1" in
  start)
    stat_busy "Starting Privoxy"
    # create missing logfiles
    for f in logfile jarfile; do 
        touch "/var/log/privoxy/${f}"
        chgrp "${PRIVOXY_GROUP}" "/var/log/privoxy/${f}"
        chmod 0660 "/var/log/privoxy/${f}"
    done
    [ -z "$PID" ] && /usr/sbin/privoxy --user ${PRIVOXY_USER}.${PRIVOXY_GROUP} \
                                       ${PRIVOXY_ARGS} ${PRIVOXY_CONF}
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon privoxy
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Privoxy"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon privoxy
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
