post_install() {
  if ! getent passwd rabbitmq &>/dev/null; then
    groupadd -r -g 197 rabbitmq &>/dev/null
    useradd -r -u 197 -g rabbitmq -d /var/lib/rabbitmq -s /bin/nologin -c 'RabbitMQ user' rabbitmq &>/dev/null
    passwd -l rabbitmq &>/dev/null
  fi
  sed -e "/NODENAME/s/rabbit$/rabbit@$(hostname -s)/" -i /etc/rabbitmq/rabbitmq-env.conf
}

post_upgrade() {
  post_install
  usermod -s /bin/nologin rabbitmq &>/dev/null
}

# vim: ts=2 sw=2 et:
