#!/bin/sh
##  The contents of this file are subject to the Mozilla Public License
##  Version 1.1 (the "License"); you may not use this file except in
##  compliance with the License. You may obtain a copy of the License
##  at http://www.mozilla.org/MPL/
##
##  Software distributed under the License is distributed on an "AS IS"
##  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
##  the License for the specific language governing rights and
##  limitations under the License.
##
##  The Original Code is RabbitMQ.
##
##  The Initial Developer of the Original Code is GoPivotal, Inc.
##  Copyright (c) 2007-2014 GoPivotal, Inc.  All rights reserved.
##

# Escape spaces and quotes, because shell is revolting.
for arg in "$@" ; do
	# Escape quotes in parameters, so that they're passed through cleanly.
	arg=$(sed -e 's/"/\\"/g' <<-END
		$arg
		END
	)
	CMDLINE="${CMDLINE} \"${arg}\""
done

SCRIPT="$(basename "$0")"

if [ $(id -u) = $(id -u rabbitmq) ] && [ "$SCRIPT" = "rabbitmq-server" ]; then
	cd /var/lib/rabbitmq
    /usr/lib/rabbitmq/bin/rabbitmq-server "$@" > "/var/log/rabbitmq/startup_log" 2> "/var/log/rabbitmq/startup_err"
elif [ $(id -u) = $(id -u rabbitmq) ]; then
	cd /var/lib/rabbitmq
    if [ -f "${PWD}/.erlang.cookie" ] ; then
        export HOME=.
    fi
    "/usr/lib/rabbitmq/bin/${SCRIPT}" "$@"
elif [ $(id -u) = 0 ] ; then
	cd /var/lib/rabbitmq
    su rabbitmq -s /bin/sh -c "/usr/lib/rabbitmq/bin/${SCRIPT} ${CMDLINE}"
else
    "/usr/lib/rabbitmq/bin/${SCRIPT}"
    echo
    echo "Only root or rabbitmq should run ${SCRIPT}"
    echo
    exit 1
fi
