post_install() {
  echo "update desktop mime database..."
  update-desktop-database -q
  update-mime-database usr/share/mime 1>&2 > /dev/null
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}

post_upgrade() {
  post_install $1

  if [ ${2%%_*} == "3.0a1" ]; then
    echo "There were lots of changes to the behavior of the majority of tools."
    echo "This may cause your files to look differently than before."
  fi
}

post_remove() {
  post_install $1
}


# vim:set ts=2 sw=2 et:
