
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='tomlkit',
    version='0.7.0',
    description='Style preserving TOML library',
    python_requires='!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<4.0,>=2.7',
    project_urls={"homepage": "https://github.com/sdispater/tomlkit", "repository": "https://github.com/sdispater/tomlkit"},
    author='Sébastien Eustace',
    author_email='sebastien@eustace.io',
    license='MIT',
    packages=['tomlkit'],
    package_dir={"": "."},
    package_data={},
    install_requires=['enum34==1.*,>=1.1.0; python_version == "2.7.*" and python_version >= "2.7.0"', 'functools32==3.*,>=3.2.3; python_version == "2.7.*" and python_version >= "2.7.0"', 'typing==3.*,>=3.6.0; python_version == "2.7.*" and python_version >= "2.7.0" or python_version == "3.4.*" and python_version >= "3.4.0"'],
    extras_require={"dev": ["black==19.*,>=19.3.0.b0", "codecov==2.*,>=2.0.0", "isort==5.*,>=5.2.0; python_version == \"3.*\" and python_version >= \"3.6.0\"", "pre-commit==1.*,>=1.10.0", "pytest==4.*,>=4.6.0", "pytest-cov==2.*,>=2.5.0", "pyyaml==5.3.*,>=5.3.1", "tox==3.*,>=3.1.0"]},
)
