
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='sphinx_inline_tabs',
    version='2020.10.19.beta4',
    description='Add inline tabbed content to your Sphinx documentation.',
    python_requires='>=3.5',
    project_urls={"homepage": "https://github.com/pradyunsg/sphinx-inline-tabs"},
    author='Pradyun Gedam',
    author_email='mail@pradyunsg.me',
    packages=['sphinx_inline_tabs'],
    package_dir={"": "src"},
    package_data={"sphinx_inline_tabs": ["static/*.css", "static/*.js"]},
    install_requires=[],
    extras_require={"doc": ["furo", "myst-parser", "sphinx>=3"], "test": ["pytest", "pytest-cov", "pytest-xdist"]},
)
