
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='yaspin',
    version='2.1.0',
    description='Yet Another Terminal Spinner',
    python_requires='==3.*,>=3.6.2',
    project_urls={"documentation": "https://github.com/pavdmyt/yaspin/blob/master/README.rst", "homepage": "https://github.com/pavdmyt/yaspin", "repository": "https://github.com/pavdmyt/yaspin"},
    author='Pavlo Dmytrenko',
    author_email='mail@pavdmyt.com',
    license='MIT',
    keywords='spinner console terminal loader indicator',
    classifiers=['Development Status :: 5 - Production/Stable', 'Environment :: Console', 'Environment :: MacOS X', 'Environment :: Other Environment', 'Intended Audience :: Developers', 'Intended Audience :: End Users/Desktop', 'Intended Audience :: Other Audience', 'Intended Audience :: System Administrators', 'License :: OSI Approved :: MIT License', 'Natural Language :: English', 'Operating System :: MacOS :: MacOS X', 'Operating System :: POSIX :: Linux', 'Programming Language :: Python', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9', 'Programming Language :: Python :: Implementation', 'Programming Language :: Python :: Implementation :: CPython', 'Programming Language :: Python :: Implementation :: PyPy', 'Topic :: Software Development', 'Topic :: Software Development :: Libraries :: Python Modules', 'Topic :: Software Development :: User Interfaces', 'Topic :: System :: Logging', 'Topic :: System :: Monitoring', 'Topic :: System :: Shells', 'Topic :: Terminals', 'Topic :: Utilities'],
    packages=['yaspin'],
    package_dir={"": "."},
    package_data={"yaspin": ["data/*.json"]},
    install_requires=['dataclasses==0.*,>=0.8.0; python_version == "3.6.*" and python_version >= "3.6.0"', 'termcolor==1.*,>=1.1.0'],
    extras_require={"dev": ["black==21.*,>=21.5.0.b1", "flake8==3.*,>=3.9.2", "isort==5.*,>=5.8.0", "pylint==2.*,>=2.8.2", "pytest==6.*,>=6.2.4", "pytest-cov==2.*,>=2.12.0", "pytest-sugar==0.*,>=0.9.4", "pytest-xdist==2.*,>=2.2.1", "twine==3.*,>=3.4.1"]},
)
