post_install() {

  if [ ! "`grep ^stb-admin: etc/group`" ]; then
        echo "adding new group: stb-admin"
        usr/sbin/groupadd stb-admin >/dev/null
        echo
  fi
  
  echo "==> Add your user to stb-admin group with:"
  echo "==> gpasswd -a user stb-admin"
  echo
  echo "==> You should add stbd to your DAEMONS list"
  echo "==> in /etc/rc.conf"
  
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  groupdel stb-admin &> /dev/null
}

post_remove() {
  /bin/true
}

