post_install() {
  systemd-sysusers toxcore.conf
  [[ -d var/lib/tox-bootstrapd ]] || install -dm 750 -o tox-bootstrapd -g tox-bootstrapd var/lib/tox-bootstrapd
}

post_upgrade() {
  (( $(vercmp $2 '3523-1') < 0 )) && systemd-sysusers toxcore.conf || true
  (( $(vercmp $2 '3523-2') < 0 )) && ([[ -d var/lib/tox-bootstrapd ]] || install -dm 750 -o tox-bootstrapd -g tox-bootstrapd var/lib/tox-bootstrapd || true
}
