post_upgrade() {
  if [ "$(vercmp $2 0.35-2)" -lt 0 ]; then
    echo ">>>"
    echo ">>> IMPORTANT UFW UPGRADE NOTICE"
    echo ">>> ----------------------------"
    echo ">>> Version 0.35 has moved several config files."
    echo ">>> You may need to copy your versions of the files"
    echo ">>> to the new location."
    echo ">>> /usr/lib/ufw/user.rules.pacsave  -> /etc/ufw/user.rules"
    echo ">>> /usr/lib/ufw/user6.rules.pacsave -> /etc/ufw/user6.rules"
    echo ">>>"
  fi
}
