post_upgrade() {
  ! grep -q 'cdemu' /etc/group && groupadd cdemu
  echo "  > Updating module dependencies..."
  EXTRAMODULES='extramodules-3.4-ARCH'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)
}


post_install() {
  echo "  > Adding 'cdemu' group"
  ! grep -q 'cdemu' /etc/group && groupadd cdemu
  echo "  > Add 'vhba' to your modules array to autoload it"
  post_upgrade
}

post_remove() {
  post_upgrade
  echo "Removing 'cdemu' group"
  groupdel cdemu
}

# vim:set ts=2 sw=2 et:
