post_install() {
	echo -n "Updating font cache... "
	mkfontscale /usr/share/fonts/wenquanyi/wqy-microhei-lite
	mkfontdir /usr/share/fonts/wenquanyi/wqy-microhei-lite
	fc-cache -s /usr/share/fonts/wenquanyi/wqy-microhei-lite
	echo "done."
}

post_upgrade() {
	post_install $1
}

post_remove() {
	rm -r /usr/share/fonts/wenquanyi/wqy-microhei-lite
	rmdir --ignore-fail-on-non-empty /usr/share/fonts/wenquanyi/
}

op=$1
shift

$op $*
