updatedesktopdtb() {
  [ -x /usr/bin/update-desktop-database ] \
    && update-desktop-database -q
  [ -x /usr/bin/update-mime-database ] \
    && update-mime-database usr/share/mime > /dev/null 2>&1
}

post_install() {
  updatedesktopdtb
	echo
  echo " >>> zim package need a browser to work properly"
  echo " >>> you can choose a browser like firefox, chromium, konqueror, ..."
}

post_upgrade() {
  updatedesktopdtb
}

post_remove() {
  updatedesktopdtb
}
