post_install() {
  cat << EOF
!NOTE!
  bitwarden_rs is now vaultwarden:
  https://github.com/dani-garcia/vaultwarden/discussions/1642

  If upgrading from bitwarden_rs, do not to leave around files/directories
  owned by the old bitwarden_rs user/group before removing the old bitwarden_rs
  user/group.

Configure the server via its environment variables in /etc/vaultwarden.env.

If vaultwarden is run at ports >1024, you should apply these systemd unit
options via a drop-in file:
[Service]
CapabilityBoundingSet=
AmbientCapabilities=
PrivateUsers=yes

If the service produces too much noise in your journal, you can redirect stdout
to /dev/null (vaultwarden will still also write to /var/log/vaultwarden.log if
configured to do so):
[Service]
StandardOutput=null

Create or edit drop-in file:
# systemctl edit vaultwarden

Start vaultwarden and enable its systemd service:
# systemctl enable --now vaultwarden
EOF
}
