#!/bin/bash

if [ -e "/etc/rc.d/openntpd" ]; then
	case "$2" in
		up)
			/etc/rc.d/openntpd start
		;;
		vpn-up)
			/etc/rc.d/openntpd start
		;;
		down)
			/etc/rc.d/openntpd stop
		;;
		vpn-down)
			/etc/rc.d/openntpd stop
		;;
	esac
fi
