post_install() {
  cat << EOF

>>> Theme management seems to be broken since version 1.7.25, btw seems quite resolved in 1.7.29
>>> If you get black background widgets, or an empty themes list, try this steps: 
>>>
>>>   delete configure file -> rm ~/.config/fox.rc
>>>   launch ControlPanel-1.7, you'll notice themes list is empty
>>>   hit Close than Save
>>>   launch ControlPanel-1.7, themes are back again

EOF
}

post_upgrade() {
  post_install
}