post_install() {
  which xdg-icon-resource 1>/dev/null 2>/dev/null && xdg-icon-resource forceupdate || true
  update-mime-database usr/share/mime
}

post_upgrade() {
  which xdg-icon-resource 1>/dev/null 2>/dev/null && xdg-icon-resource forceupdate || true
  update-mime-database usr/share/mime
}

post_remove() {
  which xdg-icon-resource 1>/dev/null 2>/dev/null && xdg-icon-resource forceupdate || true
  update-mime-database usr/share/mime
}
