post_install() {
   echo "    dpkg installs Debian package manager."
   echo "    This is useful for those who want to create/modify DEB files."
   echo "    However, *do not* use dpkg to install Debian packages in your ArchLinux machine."
   echo "    This will break your system!"
   echo "    You will need to go back to Arch wiki and read the installation guide again."
   echo "    You've been warned!"
}
