post_install() {
  useradd -s /usr/lib/neatx/nxserver-login-wrapper nx &> /dev/null
  mkdir -p ~nx/.ssh
  chown -R nx ~nx
  cp /usr/share/neatx/authorized_keys.nomachine ~nx/.ssh/authorized_keys
  chmod 600 ~nx/.ssh/authorized_keys
  grep -q '/opt/NX/lib' etc/ld.so.conf || echo '/opt/NX/lib' >> etc/ld.so.conf
}

pre_remove() {
  userdel nx > /dev/null 2>&1
  rm -rf ~nx
}

post_remove() {
  sed  -ie '/\/opt\/NX\/lib/d' etc/ld.so.conf
}

