# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=cairo
pkgname=ruby-$_gemname
pkgver=1.15.9
pkgrel=1
pkgdesc='Ruby bindings for cairo'
arch=(i686 x86_64)
url='http://cairographics.org/rcairo'
license=(Ruby)
depends=(ruby cairo ruby-pkg-config)
makedepends=(ruby-native-package-installer)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha512sums=('f934a0ad283145bb4710374ccb1b149c6f6bcdc69978cbcd45de8a9da319a4611249262b6ca4f8bd5ef3955739c54b24bb278e36c421cd0af91ed14a43eb7e98')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/COPYING" "$pkgdir/usr/share/licenses/$pkgname/COPYING"
}
