# arg 1:  the new package version
post_install() {
  # https://wiki.archlinux.org/index.php/DeveloperWiki:UID_/_GID_Database
  getent group unifi >/dev/null || groupadd -g 113 unifi
  getent passwd unifi >/dev/null || useradd -M -d /usr/lib/unifi -u 113 -g 113 unifi
  :
}

# arg 1:  the old package version
post_remove() {
  userdel -f unifi &>/dev/null
  groupdel unifi &>/dev/null
  :
}

# vim:set ts=2 sw=2 et:
