post_install () {
  echo "==> To enable url-select add the following to ~/.Xdefaults or ~/.Xresources"
  echo "==> (change to whatever suits your needs)"
  echo "==> URxvt.perl-ext-common:  default,url-select"
  echo "==> URxvt.keysym.M-u:       perl:url-select:select_next"
  echo "==> URxvt.urlLauncher:      firefox"
  echo "==> URxvt.underlineURLs:    true"
}

post_upgrade () {
  post_install $1
}

