post_install() {
  /bin/cat << EOF

===> virtualbox-ose post-install message:

===> In order to run VirtualBox, you have to
===> be in the 'vboxusers' group.
===>
===> vditool is obsolete. You should use vboxmanage to convert images.
===>
===> You have to start the VirtualBox XPCOM daemon (vboxsvc)
===> before starting one of VirtualBox frontends
===> (but it will be started automatically if you forget to do it yourself).
===>
===> If you want to be able to install guest additions, you have to install
===> 'virtualbox-additions' package.
===>
===> The last user manual is available for download at:
===> http://www.virtualbox.org/download/UserManual.pdf
===>

EOF
}
