post_install() {
    systemd-sysusers elasticsearch.conf
    systemd-tmpfiles --create elasticsearch.conf
    chown -R elasticsearch:elasticsearch /usr/share/elasticsearch
}

post_upgrade(){
    systemd-sysusers elasticsearch.conf
    systemd-tmpfiles --create elasticsearch.conf
}

post_remove() {
    if getent passwd elasticsearch >/dev/null 2>&1; then
        userdel elasticsearch
    fi
    if getent group elasticsearch >/dev/null 2>&1; then
        groupdel elasticsearch
    fi
}
