post_install() {
  useradd -d /opt/NX/home/nx -s /usr/lib/neatx/nxserver-login-wrapper nx &> /dev/null
  mkdir -p ~nx/.ssh
  cp /usr/share/neatx/authorized_keys.nomachine ~nx/.ssh/authorized_keys
  chmod 600 ~nx/.ssh/authorized_keys
  chown -R nx ~nx
  post_remove
}

pre_remove() {
  userdel nx > /dev/null 2>&1
  rm -rf ~nx
}

post_remove() {
  sed  -e '/\/opt\/NX\/lib/d' -i etc/ld.so.conf
  ldconfig
}
