#!/bin/bash

LIBDIR="@LIBDIR@"

if [[ -e "$LIBDIR/libv4l/v4l2convert.so" ]]; then
	export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}$LIBDIR/libv4l/v4l2convert.so"
fi

if [[ -e "/usr/share/skype/lib/libQtWebKit.so.4" ]]; then
	export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}/usr/share/skype/lib/libQtWebKit.so.4"
fi

PULSE_LATENCY_MSEC=30 exec "$LIBDIR/skype/skype" "$@"
