# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=glib2
pkgname=ruby-$_gemname
pkgver=3.3.3
pkgrel=1
pkgdesc='Ruby/GLib2 is a Ruby binding of GLib-2.x.'
arch=(x86_64)
url='http://ruby-gnome2.sourceforge.jp/'
license=(LGPL2.1)
depends=(ruby glib2 ruby-pkg-config ruby-native-package-installer)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('20116f9813f9bd6f3a36ef3aba08a40e0dd64501')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --no-document --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
