--- Makefile.in	2008-05-25 17:44:34.000000000 +0200
+++ Makefile.in.new	2008-08-10 15:12:37.000000000 +0200
@@ -677,11 +677,11 @@
 	   cp scripts/gadmin-samba-pdf $(bindir)/; \
 	fi;
 	@echo Installing example logon script to static /home/netlogon.
-	if test ! -d /home/netlogon; then \
-	   mkdir -p /home/netlogon; \
+	if test ! -d $(DESTDIR)/usr/share/gadmin-samba; then \
+	   mkdir -p $(DESTDIR)/usr/share/gadmin-samba; \
 	fi;
-	if test -d /home/netlogon && test ! -f /home/netlogon/example.bat; then \
-	   cp scripts/example.bat /home/netlogon/; \
+	if test -d $(DESTDIR)/usr/share/gadmin-samba && test ! -f $(DESTDIR)/usr/share/gadmin-samba/example.bat; then \
+	   cp scripts/example.bat $(DESTDIR)/usr/share/gadmin-samba/; \
 	fi;
 	@echo ""
 	@echo "Start GADMIN-SAMBA by typing gadmin-samba in a terminal"
