post_install() {
  # TODO: move it to systemd-sysusers format
  if ! getent group mldonkey >/dev/null; then
    groupadd --system mldonkey
  fi
  if ! getent passwd mldonkey >/dev/null; then
    useradd --system -c 'Mldonkey daemon user' -g mldonkey -d /var/lib/mldonkey -s /bin/false mldonkey
  fi

  mkdir -p /var/lib/mldonkey
  chown mldonkey:mldonkey /var/lib/mldonkey
}

post_upgrade() {
  post_install $1
}
