## arg 1:  the new package version
post_install() {
  echo "Make sure to add your user to the games group to play dwarffortress"
  post_upgrade $1 0
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  # Make sure that permissions are correct
  chown -R root:games /opt/df_linux/data
  find /opt/df_linux/data/save -type d -exec chmod 775 {} + &
  find /opt/df_linux/data/save -type f -exec chmod 664 {} + &
}

# vim:set ts=2 sw=2 et:
