#!/bin/bash

# a basic script for maximum pretty

# X-based modes
if [[ -n "$DISPLAY" && -x /usr/bin/aterm ]]; then
  exec aterm -fn mtx -e cmatrix -abox
  exit
fi
if [[ -n "$DISPLAY" && -x /usr/bin/xterm ]]; then
  exec xterm -fn mtx -en iso1252 -e cmatrix -abx
  exit
fi

# safe mode
if [[ "$TERM" != "linux" ]]; then
    exec cmatrix -abo
    exit
fi

# custom font mode
setfont matrix
cmatrix -abol

# and put the font back, if possible
default_font=""
if [[ -f /etc/vconsole.conf ]]; then
    default_font="$(grep '^[ \t]*FONT' /etc/vconsole.conf | cut -d '=' -f 2)"
fi
if [[ -n "$default_font" ]]; then
    setfont "$default_font"
fi

