post_install() {
  systemd-sysusers squid.conf
  systemd-tmpfiles --create squid.conf
  chown proxy:proxy var/{cache,log}/squid
  echo "- squid-rotate.timer is not enabled by default"
}

post_upgrade() {
  post_install
  if [ `vercmp "$2" "3.5.4-1"` -le 0 ]; then
    echo "- Add 'dns_v4_first on' option into config unless your provider support ipv6!"
  fi
  if [ `vercmp "$2" "3.5.21-1"` -le 0 ]; then
    echo "- squid-rotate.timer is not enabled by default"
  fi
}
