pkgname=shotwell

post_install() {
  gtk-update-icon-cache -fq -t /usr/share/icons/hicolor
  update-desktop-database -q
  usr/sbin/gconfpkg --install ${pkgname}
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  gtk-update-icon-cache -fq -t /usr/share/icons/hicolor
  update-desktop-database -q
}
