--- Makefile.copy	2009-12-31 10:24:57.000000000 +0200
+++ Makefile	2010-01-01 03:12:06.000000000 +0200
@@ -63,7 +63,7 @@ xdo.c: xdo.h
 xdotool.c: xdo.h
 
 libxdo.so: xdo.o
-	$(LD) $(LDFLAGS) -shared -soname=libxdo.so.$(MINOR) $< -o $@
+	$(CC) $(LDFLAGS) -shared -Wl,-soname=libxdo.so.$(MINOR) $< -o $@
 
 xdotool: xdotool.o xdo.o
 	$(CC) $(CFLAGS) xdotool.o xdo.o $(LDFLAGS) -o $@
