# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman
# Contributor: François Charette <firmicus ατ gmx δοτ net>

pkgname=perl-class-data-inheritable
pkgver=0.09
pkgrel=3
pkgdesc="Inheritable, overridable class data "
arch=('x86_64')
url="https://search.cpan.org/dist/Class-Data-Inheritable"
license=('GPL' 'PerlArtistic')
depends=('perl>=5.10.0')
options=('!emptydirs')
source=(https://cpan.metacpan.org/authors/id/R/RS/RSHERER/Class-Data-Inheritable-$pkgver.tar.gz)
sha256sums=('44088d6e90712e187b8a5b050ca5b1c70efe2baa32ae123e9bd8f59f29f06e4d')

build() {
  cd  Class-Data-Inheritable-${pkgver}
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor
  make
}

package() {
  cd  Class-Data-Inheritable-${pkgver}
  make install DESTDIR="$pkgdir"
  find "$pkgdir" -name '.packlist' -delete
  find "$pkgdir" -name '*.pod' -delete
}
