# arg 1:  the new package version
post_install() {
	# we need to ldconfig first, in case xfree86's libs aren't
	# in ld.so.cache yet
	sbin/ldconfig -r .
	usr/bin/pango-querymodules-32 >etc/pango/pango.modules-32
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	if [ -f etc/pango/pango.modules-32 ]; then
		rm etc/pango/pango.modules-32
	fi
	post_install $1
}

# arg 1:  the old package version
pre_remove() {
	rm etc/pango/pango.modules-32
}
