post_install() {
	echo "To add this script to your WeeChat installation, please execute the following command:"
	echo "ln -s /usr/share/weechat/python/weechat-matrix.py -t ~/.weechat/python"
}

post_upgrade() {
	if [ "$2" = "0.1.0-1" ]
	then
		echo "The location of the script has changed, please update your symbolic links:"
		echo "rm ~/.weechat/python/{matrix,matrix.py}"
		echo "ln -s /usr/share/weechat/python/weechat-matrix.py -t ~/.weechat/python"
	fi
}
