post_install() {
  echo "The roundcube install folder has been renamed to 'xinstallerx' with no access rights for security reasons."
  echo "However, it is recommended that it be removed to maintain optimal security."
  chmod ugo-rwx usr/share/webapps/roundcubemail/xinstallerx
  chown -R http:http var/log/roundcubemail
}

post_upgrade() {
  post_install
  echo "Since 0.7.2-2 rouncubemail is in /usr/share/webapps/"
}
