post_install() {
  gtk-update-icon-cache -q -f -t /usr/share/icons/hicolor
  update-desktop-database -q
  echo 'If you use a lightweight windowmanager, remember to run'
  echo '/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 to enable'
  echo 'graphical authentication, which may be needed for pkexec to work.'
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}

# vim:set ts=2 sw=2 et:
