post_upgrade() {
  echo "  > The 'cdemu' group is now created by vhba-module"
  echo "  >> you may have to re-add yourself to the group and relogin"
  echo
  echo "  > Daemon can be used in session mode as user, simply run 'cdemud'"
  echo "    >> you do not need to use the init script in this case"
  echo "    >> put your configuration in ~/.cdemud instead"
}

post_install () {
  echo "  > Add yourself to the 'cdemu' group for non-root access"
  echo "  > Start the daemon as root with /etc/rc.d/cdemud"
  echo "  > See /etc/conf.d/cdemud for further configuration"
  echo
  echo "  > Daemon can be used in session mode as user, simply run 'cdemud'"
  echo "    >> you do not need to use the init script in this case"
  echo "    >> put your configuration in ~/.cdemud instead"
}

# vim:set ts=2 sw=2 et:
