post_install () {
  cat <<MSG
  > Only users with at a physical terminal or in the 'cdemu'
    group can communicate with the system daemon or make use
    of a session daemon.

  > If you want to output CD-Audio you need to use a session
    daemon, e.g. via "cdemu -b session". If you use ALSA and
    not PulseAudio, echo AUDIO_DRIVER=alsa > ~/.cdemu-daemon

  > The daemons are usually started on-demand, but a system
    daemon can be manually started via cdemu-daemon.service.
    See /etc/conf.d/cdemu-daemon for further configuration.

MSG

  post_upgrade $1 $1

  modprobe vhba

  return 0
}

post_upgrade () {
  if (( $(vercmp $2 2.0.0) < 0)); then
    cat <<MSG
  > Configuration files and log files have been renamed in
    order to bring Arch closer to upstream. In particular,
    this affects:
      /etc/conf.d/cdemud  --> /etc/conf.d/cdemu-daemon
      /var/log/cdemud.log --> /var/log/cdemu-daemon.log
      ~/.cdemud           --> ~/.cdemu-daemon
      ~/.cdemud.log       --> ~/.cdemu-daemon.log
    Please move your configuration.

MSG
  fi

  return 0
}

# vim:set ts=2 sw=2 et:
