#!/bin/sh

cp -ru /usr/share/higan ~/.config/

prompt="$(zenity --list --radiolist --title 'Please select a profile' --column '' --column '' FALSE 'Icarus' FALSE 'Tomoko (accuracy)' TRUE 'Tomoko (balanced)' FALSE 'Tomoko (performance)')"

case $prompt in
  'Icarus')
    exec icarus
    ;;
  'Tomoko (accuracy)')
    exec tomoko-accuracy
    ;;
  'Tomoko (balanced)')
    exec tomoko-balanced
    ;;
  'Tomoko (performance)')
    exec tomoko-performance
    ;;
esac

# vim: ts=2 sw=2 et:
