#!/bin/sh
#
# Runs jEdit - Programmer's Text Editor.
#

# Set jvm heap initial and maximum sizes (in megabytes).
JAVA_HEAP_MAX_SIZE=192

DEFAULT_JAVA_HOME="/usr/lib/jvm/java-6-openjdk/jre"
if [ -z "$JAVA_HOME" ]; then
	JAVA_HOME="$DEFAULT_JAVA_HOME"
fi

# Launch application.

exec "$JAVA_HOME/bin/java" -Xmx${JAVA_HEAP_MAX_SIZE}M -jar "/usr/share/java/jedit/jedit.jar" "$@"
