post_install() {
  post_upgrade
}

_config_instructions() {
  echo "If you plan to use external client (e.g. amuleGUI or amuleweb) then you need to"
  echo "provide [ExternalConnect] configuration."
  echo "You also need to specify amuleweb password."
  echo "Please follow https://wiki.archlinux.org/index.php/AMule for more information."
  echo "amuleweb can be started as 'systemctl start amuleweb'."
}

post_upgrade() {
  if [ ! -e /var/lib/amule/.aMule/amule.conf ]; then
    _config_instructions
  fi
}
