post_upgrade() {
  echo
  echo 'See http://doc.powerdns.com/md/authoritative/upgrading/ for'
  echo 'information about changes when upgrading.'
  echo
  echo 'If upgrading from an older version, you may also need to:'
  echo 'setconf /etc/powerdns/pdns.conf module-dir=/usr/lib/powerdns'
  echo
  echo 'NOTE: pdns.service has been renamed to powerdns.service.'
  echo '      See FS#44642 for more information.'
  echo
}

# vim:set ts=2 sw=2 et:
