diff -druN src.orig/makefile src/makefile
--- src.orig/makefile	2013-02-14 18:26:28.000000000 +0100
+++ src/makefile	2013-02-15 14:34:54.082756900 +0100
@@ -12,6 +12,7 @@
 gflags = -c $(includedirs) -g
 
 cflags = $(gflags) # the default setting
+cflags = -c $(includedirs) -O2 -fPIC -g -DFAST -DALLTRUE
 
 ifdef optimize
 	NDEBUG = true
@@ -22,18 +23,64 @@
 	cflags = $(pflags)
 endif
 
-cc = g++
+EXENAME = coxeter
+LIBNAME = coxeter3
+ifeq ($(UNAME),Darwin)
+	EXEEXT = 
+	LIBPREFIX = lib
+	LIBEXT = .dylib
+	LIBDIR = lib
+	LINKFLAGS = -dynamiclib -Wl,-headerpad_max_install_names,-undefined,dynamic_lookup,-compatibility_version,3.0,-current_version,3.0,-install_name,$(SAGE_LOCAL)/lib/$(LIBPREFIX)$(LIBNAME)$(LIBEXT)
+	LINKLIBS = 
+else
+ifeq ($(UNAME),CYGWIN)
+	EXEEXT = .exe
+	LIBPREFIX = cyg
+	LIBEXT = .dll
+	LIBDIR = bin
+	IMPLIB = lib$(LIBNAME).dll.a
+	LINKFLAGS = -shared -Wl,--out-implib=$(IMPLIB) -Wl,--export-all-symbols
+	LINKLIBS = -lc
+else
+	EXEEXT = 
+	LIBPREFIX = lib
+	LIBEXT = .so
+	LIBDIR = lib
+	LINKFLAGS = -shared -Wl,-soname,libcoxeter3.so
+	LINKLIBS = -lc
+endif
+endif
+LIBRARY = $(LIBPREFIX)$(LIBNAME)$(LIBEXT)
 
-all: coxeter #clean
+all: coxeter executable
 
 coxeter: $(objects)
-	$(cc) -o coxeter $(objects)
+	$(CXX) $(LINKFLAGS) -o $(LIBRARY) $(objects) $(LINKLIBS)
+
+executable: $(objects)
+	$(CXX) -o $(EXENAME)$(EXEEXT) $(objects)
+
+DATADIR="$(INSTALL_DIR)/share/coxeter/"
+INCLUDEDIR="$(INSTALL_DIR)/include/coxeter/"
+LIBRARYDIR="$(INSTALL_DIR)/lib/"
+
+install: coxeter executable
+	cp $(EXENAME)$(EXEEXT) "$(INSTALL_DIR)/bin/"
+	cp $(LIBRARY) $(LIBRARYDIR)
+	if [ $(UNAME) = "CYGWIN" ]; then                 \
+	    cp $(IMPLIB) "$$SAGE_LOCAL/lib/";  \
+	fi
+
+	mkdir -p $(DATADIR)
+	cp -r coxeter_matrices headers messages $(DATADIR)
+	mkdir -p $(INCLUDEDIR)
+	cp -r *.h *.hpp $(INCLUDEDIR)
 
 clean:
 	rm -f $(objects)
 
 %.o:%.cpp
-	$(cc) $(cflags) $*.cpp
+	$(CXX) $(cflags) $*.cpp
 
 # dependencies --- these were generated automatically by make depend on my
 # system; they are explicitly copied for portability. Only local dependencies
@@ -33,7 +90,7 @@
 # contents of tmp in lieu of the dependencies listed here.
 
 %.d:%.cpp
-	@$(cc) -MM $*.cpp
+	@$(CXX) -MM $*.cpp
 depend: $(dependencies)
 
 affine.o: affine.cpp affine.h globals.h coxgroup.h coxtypes.h io.h list.h \
@@ -142,6 +199,7 @@
 posets.o: posets.cpp posets.h globals.h bits.h list.h memory.h \
   constants.h list.hpp error.h io.h wgraph.h interface.h automata.h \
   coxtypes.h minroots.h dotval.h graph.h type.h transducer.h
+sage.o: sage.cpp sage.h globals.h coxtypes.h coxgroup.h list.h schubert.h
 schubert.o: schubert.cpp schubert.h globals.h coxtypes.h io.h list.h \
   memory.h constants.h list.hpp error.h bits.h interface.h automata.h \
   minroots.h dotval.h graph.h type.h transducer.h stack.h stack.hpp
