#!/bin/sh

# arg 1:  the new package version
post_install() {
  getent group vboxsf > /dev/null || groupadd --system vboxsf
  true
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install "$1"
  if [ "`vercmp $2 4.1.18-3`" -lt 0 ]; then
    cat << EOF
==> rc.d vbox-service script was renamed to vboxservice.
EOF
  fi
  true
}

# arg 1:  the old package version
post_remove() {
  groupdel vboxsf >/dev/null 2>&1 || true
}

# vim:set ts=2 sw=2 ft=sh et:
