#/bin/bash

# arg 1:  the new package version
post_install() {
  # https://wiki.archlinux.org/index.php/DeveloperWiki:UID_/_GID_Database
  getent group lldpd >/dev/null || groupadd -g 127 lldpd
  getent passwd lldpd >/dev/null || useradd -d /run/lldpd -u 127 -g 127 lldpd
  systemd-tmpfiles --create lldpd.conf
  true
}

# arg 1:  the old package version
post_remove() {
  userdel -f lldpd &>/dev/null
  groupdel lldpd &>/dev/null
  true
}

# vim:set ts=2 sw=2 ft=sh et:
