post_install() {
  xdg-desktop-menu forceupdate &> /dev/null || :
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null || :
}

post_upgrade() {
  xdg-desktop-menu forceupdate &> /dev/null || :
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null || :
}

post_remove() {
  xdg-desktop-menu forceupdate &> /dev/null || :
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null || :
}
