post_install() {
  which xdg-icon-resource 1>/dev/null 2>/dev/null && xdg-icon-resource forceupdate || true
  cat << EOF
    Install at least one of the following search backends for catfish:
      'findutils', 'slocate', 'tracker', 'beagle', 'strigi' or 'pinot'
EOF
}

post_upgrade() {
  which xdg-icon-resource 1>/dev/null 2>/dev/null && xdg-icon-resource forceupdate || true
}

post_remove() {
  which xdg-icon-resource 1>/dev/null 2>/dev/null && xdg-icon-resource forceupdate || true
}
