#!/bin/bash

. /etc/conf.d/inputattach

case "$1" in
	start)
		for i in "${IAPARAMS[@]}"; do
			/usr/bin/inputattach --daemon $i || exit 1
		done
		;;
	stop)
		killall inputattach || exit 1
		;;
esac
