post_install() {
  grep -qs ^minbif: /etc/group || groupadd -g 67 minbif
  grep -qs ^minbif: /etc/passwd || useradd -u 67 -g minbif \
    -d /var/lib/minbif -s /bin/false minbif

  chown -R minbif:minbif /var/lib/minbif
  chmod 0770 /var/lib/minbif
  chmod 0770 /var/lib/minbif/users
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  grep -qs ^minbif: /etc/passwd && userdel minbif
  grep -qs ^minbif: /etc/group && groupdel minbif
}
