post_install() {
cat << EOF
===> You may want to load vboxguest, vboxsf and vboxvideo
EOF
    EXTRAMODULES='extramodules-3.7-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_upgrade() {
    EXTRAMODULES='extramodules-3.7-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='extramodules-3.7-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}
