post_install() {
  if [ ! `grep openfire /etc/group` ]; then
    groupadd openfire &>/dev/null;
  fi

  id openfire &>/dev/null || \
    useradd -g openfire -d /usr/share/openfire -s /bin/false openfire

  chown -R openfire:openfire /var/log/openfire /usr/share/openfire /etc/openfire
}

post_upgrade() {
  post_install
}

pre_remove() {
  userdel openfire &> /dev/null
  groupdel openfire &> /dev/null
}
