post_install() {
    gtk-update-icon-cache -q -t -f /usr/share/icons/ContrastHighLargePrint
    gtk-update-icon-cache -q -t -f /usr/share/icons/ContrastHighLargePrintInverse
    gtk-update-icon-cache -q -t -f /usr/share/icons/ContrastHigh-SVG
    gtk-update-icon-cache -q -t -f /usr/share/icons/Fog
    gtk-update-icon-cache -q -t -f /usr/share/icons/mate
    gtk-update-icon-cache -q -t -f /usr/share/icons/Quid
}

post_upgrade() {
    post_install
}

post_remove() {
    post_install
}
