
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='yaspin',
    version='1.2.0',
    description='Yet Another Terminal Spinner',
    python_requires='!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<4.0,>=2.7',
    project_urls={"documentation": "https://github.com/pavdmyt/yaspin/blob/master/README.rst", "homepage": "https://github.com/pavdmyt/yaspin", "repository": "https://github.com/pavdmyt/yaspin"},
    author='Pavlo Dmytrenko',
    author_email='mail@pavdmyt.com',
    license='MIT',
    keywords='spinner console terminal loader indicator',
    classifiers=['Development Status :: 5 - Production/Stable', 'Environment :: Console', 'Environment :: MacOS X', 'Environment :: Other Environment', 'Intended Audience :: Developers', 'Intended Audience :: End Users/Desktop', 'Intended Audience :: Other Audience', 'Intended Audience :: System Administrators', 'License :: OSI Approved :: MIT License', 'Natural Language :: English', 'Operating System :: MacOS :: MacOS X', 'Operating System :: POSIX :: Linux', 'Programming Language :: Python', 'Programming Language :: Python :: 2', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9', 'Programming Language :: Python :: Implementation', 'Programming Language :: Python :: Implementation :: CPython', 'Programming Language :: Python :: Implementation :: PyPy', 'Topic :: Software Development', 'Topic :: Software Development :: Libraries :: Python Modules', 'Topic :: Software Development :: User Interfaces', 'Topic :: System :: Logging', 'Topic :: System :: Monitoring', 'Topic :: System :: Shells', 'Topic :: Terminals', 'Topic :: Utilities'],
    packages=['yaspin'],
    package_dir={"": "."},
    package_data={"yaspin": ["data/*.json"]},
    install_requires=[],
    extras_require={"dev": ["flake8<3.7", "isort==4.*,>=4.3.0", "pytest==4.*,>=4.6.0", "pytest-cov==2.*,>=2.10.0", "pytest-sugar==0.*,>=0.9.0", "pytest-xdist==1.*,>=1.33.0"]},
)
