post_install() {
    groupadd -r radiusd
    useradd -r -m -d /var/lib/radiusd -g radiusd -s /bin/false radiusd

    touch var/log/radius/radius.log
    chown -R radiusd:radiusd var/log/radius/radius.log

    [ -d etc/raddb ] || {
      cp -a etc/raddb.default etc/raddb
      chown -R radiusd:radiusd etc/raddb
    }

    systemd-tmpfiles --create freeradius.conf
}

post_remove() {
    echo "-- You may want to remove /var/lib/radiusd and /etc/raddb"
}
