# arg 1:  the new package version
post_install() {
    systemd-tmpfiles --create wesnothd.conf
cat << EOF
Note:
==> If you experience sound problems try setting your SDL_AUDIODRIVER environment variable to "dma"
==> eg. export SDL_AUDIODRIVER="dma" ; wesnoth
==> If "dma" doesn't work,other options are: dsp,alsa,artsc,esd,nas try to find the right output.
EOF
}

post_upgrade() {
    post_install
}
