pre_install() {
	/bin/true
}
post_install() {
  echo '==> Note: dmd does not come with a runtime library!'
  echo '==> The D language has two competing, incompatible standard libraries.'
  echo '==> In order for dmd to be useful, you must'
  echo '==> install either libphobos or libtango, whichever you prefer.'
}
pre_upgrade() {
	/bin/true
}
post_upgrade() {
  /bin/true
}
pre_remove() {
	/bin/true
}
post_remove() {
	/bin/true
}
