post_install() {
  getent group emby > /dev/null 2>&1 || groupadd -g 422 emby
  getent passwd emby > /dev/null 2>&1 || useradd -c 'Emby Media Server' -u 422 -g emby -d /var/lib/emby -s /usr/bin/nologin emby
  passwd -l emby > /dev/null

cat <<EOF

Emby is not compatible with the 10-bit versionof libx264. Please stick to the
8-bit version if you plan on using emby's transcoding features.

EOF
}

post_upgrade() {
  post_install
}

# vim: ts=2 sw=2 et:
