#!/bin/sh

cp -u /usr/share/higan/cheats.bml ~/.config/
if [[ -d ~/Emulation ]]; then
  cp -ru /usr/share/higan/*.sys ~/Emulation/
fi

prompt="$(zenity --list --radiolist --title 'Please select a profile' --column '' --column '' FALSE 'icarus' FALSE 'higan (accuracy)' TRUE 'higan (balanced)' FALSE 'higan (performance)')"

case $prompt in
  'Icarus')
    exec icarus
    ;;
  'higan (accuracy)')
    exec higan-accuracy
    ;;
  'higan (balanced)')
    exec higan-balanced
    ;;
  'higan (performance)')
    exec higan-performance
    ;;
esac

# vim: ts=2 sw=2 et:
