update_icons() {

	# Setup Menus
	if which update-desktop-database
	then
		update-desktop-database -q /usr/share/applications
	fi

	# Setup MIME types
	if which update-mime-database
	then
		update-mime-database /usr/share/mime >/dev/null
	fi

	# Setup Icons
	touch -c /usr/share/icons/hicolor
	if which gtk-update-icon-cache
	then
		gtk-update-icon-cache -tq /usr/share/icons/hicolor
	fi

}

post_install() {
	update_icons
}

post_upgrade() {
	update_icons
}

post_remove() {
	update_icons
}
