pkgname=lxdm

post_install() {
    getent group lxdm > /dev/null 2>&1 || groupadd -g 121 lxdm
    getent passwd lxdm > /dev/null 2>&1 || useradd -c 'LXDE Display Manager' -u 121 -g lxdm -d /var/lib/lxdm -s /sbin/nologin lxdm
    passwd -l lxdm > /dev/null
    chown -R lxdm:lxdm /var/lib/lxdm > /dev/null
}

post_upgrade() {
    post_install
}

post_remove() {
    getent passwd lxdm > /dev/null 2>&1 && userdel lxdm
    getent group lxdm > /dev/null 2>&1 && groupdel lxdm
}
