--- grinvin-1.2.2/nonjava/Makefile.incl.tmpl.orig	2015-01-22 21:46:11.188829593 +0100
+++ grinvin-1.2.2/nonjava/Makefile.incl.tmpl	2015-01-22 21:46:29.078893693 +0100
@@ -37,14 +37,14 @@
 
 # Which distributions to build on which OS
 
-#TARGETS=for-linux-on-linux
-TARGETS=for-linux-on-linux for-win32-on-linux
+TARGETS=for-linux-on-linux
+#TARGETS=for-linux-on-linux for-win32-on-linux
 #TARGETS=for-osx-on-osx for-linux-on-osx for-win32-on-osx
 
 # Locations of the executables
 
 # typical linux situation:
-WIN-GCC=/usr/bin/i586-mingw32msvc-gcc
+#WIN-GCC=/usr/bin/i586-mingw32msvc-gcc
 
 # typical osx situation
 #LIN-GCC=/usr/local/i386-linux-4.1.1/bin/i386-linux-gcc
