--- Makefile.orig	2010-01-18 11:28:01.000000000 +0000
+++ Makefile	2010-01-29 14:02:13.000000000 +0000
@@ -10,7 +10,7 @@
 LOGPATH = /var/log/atop
 MAN1PATH = /usr/share/man/man1
 MAN5PATH = /usr/share/man/man5
-INIPATH = /etc/rc.d/init.d
+INIPATH = /etc/rc.d
 CRNPATH = /etc/cron.d
 ROTPATH = /etc/logrotate.d
 
