post_install() {
cat << EOF

To use radvd you must create the configuration file

  /etc/radvd.conf

An example configuration file has been installed at

  /usr/share/doc/radvd/radvd.conf.example

radvd requires IPv6 forwarding be enabled.
To enable IPv6 forwarding at boot time,
add the following line to /etc/sysctl.conf:

  # Enable IPv6 packet forwarding 
  net.ipv6.conf.all.forwarding = 1

or manually enable forwarding using:

  echo 1 > /proc/sys/net/ipv6/conf/all/forwarding 

EOF
}

op=$1
shift
$op $*
