post_install() {
cat << EOF
  WebGUI can be accessed at http://localhost:8080

  Execute

    systemctl daemon-reload

  to reload systemd modules.

  To start syncthing, execute:

    systemctl start syncthing@user

  where 'user' is your username.

  To autostart syncthing on system start, execute

    systemctl enable syncthing@user

  where 'user' is your username.

EOF
}

post_upgrade() {
    post_install
}
