post_upgrade() {
  if (( "$(vercmp $2 0.12.0-1)" < 0 )); then
    cat << EOF
  This is the first release on the new major v0.12 branch. It is not
  compatible with the v0.11.x releases! Use this release if you are
  a new user, or when you are ready to upgrade all devices in your cluster.
  Full information is available on the release page
  https://forum.syncthing.net/t/syncthing-v0-12-0-beryllium-bedbug/6026

EOF
  fi
}
