post_install() {
  cat << EOF

  Using sysvinit, make the xdm line near the end of /etc/inittab read;
    x:5:respawn:/usr/bin/xdm -nodaemon -config /etc/X11/xdm/archlinux/xdm-config

  Using systemd, execute
    systemctl enable xdm-archlinux

  If you want an xconsole on the login screen, or don't want the clock or the
  halt and reboot buttons, edit /etc/X11/xdm/archlinux/Xsetup

EOF
}

post_upgrade() {
  post_install $1
}
