# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: Alexsandr Pavlov <kidoz at mail dot ru>

_gemname=ronn-ng
pkgname=ruby-$_gemname
pkgver=0.9.1
pkgrel=5
pkgdesc='Manual page formatter that generates man pages from markdown'
arch=(any)
url='https://github.com/apjanke/ronn-ng'
license=(MIT)
depends=(ruby ruby-rdiscount ruby-mustache ruby-kramdown ruby-nokogiri)
makedepends=('ruby-rdoc')
conflicts=('ruby-ronn')
provides=('ruby-ronn')
replaces=('ruby-ronn')
options=(!emptydirs)
source=("https://rubygems.org/downloads/$_gemname-$pkgver.gem"
        '0001-allow-mustache-1.0.patch'
        'source-date-epoch.patch::https://github.com/apjanke/ronn-ng/commit/ee042749944777f37ab184cadcacb89eee2e696a.patch')
noextract=($_gemname-$pkgver.gem)
sha256sums=('d04d8fe205e018dea9bb97e3bcf60d9853a326f90714ee5082752976ca739dea'
            '9151397a0dc51392065de74bd52ab8e76e3ea5e3e810d0e557f2a67734633ea5'
            '3a7a174e0d41fc87fae4a75600fa24a35a7d3608a948124f0960f2f07664f4c6')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  patch -d "$pkgdir/$_gemdir/specifications" -i "$srcdir/0001-allow-mustache-1.0.patch"
  patch -d "$pkgdir/$_gemdir/gems/$_gemname-$pkgver" -Np1 < "$srcdir/source-date-epoch.patch"
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"

  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/man/ronn.1" "$pkgdir/usr/share/man/man1/ronn.1"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/man/ronn-format.7" "$pkgdir/usr/share/man/man7/ronn-format.7"

  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/completion/bash/ronn" "$pkgdir/usr/share/bash-completion/completions/ronn"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/completion/zsh/_ronn" "$pkgdir/usr/share/zsh/site-functions/_ronn"
}
