# arg 1:  the new package version
post_install() {
cat << EOM

If you want to use ddclient with dhcpcd, cron or pppd,
see /etc/ddclient/samples for further instructions.

EOM
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
if [ -f /etc/ddclient/ddclient.cache ]; then
	echo -n "Moving ddclient.cache from /etc/ddclient/ to /var/cache/ddclient/."
	mv /etc/ddclient/ddclient.cache /var/cache/ddclient/
	echo " (done)"
fi
}
