#!/bin/sh

export LD_LIBRARY_PATH='/usr/lib/skia-sharp58'

exec dotnet /usr/lib/emby-server/EmbyServer.dll \
  -programdata $PROGRAM_DATA \
  -ffmpeg $FFMPEG \
  -ffprobe $FFPROBE \
  -restartexitcode 3

# vim: ts=2 sw=2 et:
