post_install() {
  if ! getent group gitolite &>/dev/null; then
    groupadd -r -g 196 gitolite >/dev/null
  fi

  if ! getent passwd gitolite &>/dev/null; then
    useradd -m -r -u 196 -g gitolite -d /var/lib/gitolite \
      -s /bin/bash gitolite >/dev/null
  fi
}

post_upgrade() {
  post_install
}

post_remove() {
  if getent passwd gitolite &>/dev/null; then
    userdel gitolite >/dev/null
  fi

  if getent group gitolite &>/dev/null; then
    groupdel gitolite >/dev/null
  fi
}
