post_install() {
  getent group openfire >/dev/null 2>&1 || groupadd -r openfire &>/dev/null;
  getent passwd openfire >/dev/null 2>&1 || useradd -rg openfire -d /usr/share/openfire -s /bin/false openfire &>/dev/null

  chown -R openfire:openfire var/log/openfire usr/share/openfire etc/openfire
}

post_upgrade() {
  post_install
}

pre_remove() {
  getent passwd openfire >/dev/null 2>&1 && userdel openfire &> /dev/null
  getent group openfire >/dev/null 2>&1 && groupdel openfire &> /dev/null
}
