# Maintainer: Sergej Pupykin <pupykin.s+arch@gmail.com>
# Contributor: François Charette <firmicus ατ gmx δοτ net>
# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman

pkgname=perl-class-singleton
pkgver=1.6
pkgrel=1
pkgdesc="Implementation of a singleton class"
arch=('any')
url="https://search.cpan.org/dist/Class-Singleton"
license=('GPL' 'PerlArtistic')
depends=('perl>=5.10.0')
options=('!emptydirs')
source=("https://search.cpan.org/CPAN/authors/id/S/SH/SHAY/Class-Singleton-$pkgver.tar.gz")
md5sums=('d9c84a7b8d1c490c38e88ed1f9faae47')

build() {
  cd  "$srcdir"/Class-Singleton-$pkgver
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor
  make
}

package() {
  cd  "$srcdir"/Class-Singleton-$pkgver
  make install DESTDIR="$pkgdir"
  find "$pkgdir" -name '.packlist' -delete
  find "$pkgdir" -name '*.pod' -delete
}
