# Maintainer: Jonas Witschel <diabonas@archlinux.org>
pkgname=junit-system-rules
pkgver=1.19.0
_commit=f4782ebfd72c08bd3f00aa04ad20fe499c5463b4 # signed commit corresponding to tag system-rules-1.19.0
pkgrel=5
pkgdesc='A collection of JUnit rules for testing code that uses java.lang.System'
arch=('any')
url='https://stefanbirkner.github.io/system-rules/'
license=('CPL')
depends=('junit')
makedepends=('git' 'jdk8-openjdk' 'maven' 'strip-nondeterminism')
source=("$pkgname::git+https://github.com/stefanbirkner/system-rules.git?signed#commit=$_commit")
sha512sums=('SKIP')
validpgpkeys=('F4AF40991AECE57728B0034F9ECE1F68817F4996') # Stefan Birkner <mail@stefan-birkner.de>

build() {
	cd "$pkgname"

	# The package cannot be compiled with newer Java versions (but works fine at runtime)
	# (https://github.com/stefanbirkner/system-rules/issues/65#issuecomment-402837535)
	export PATH="/usr/lib/jvm/java-8-openjdk/bin:$PATH"

	mvn -DskipTests=true clean package

	# Timestamps in JAR files generated by Maven do not honour SOURCE_DATE_EPOCH
	# (https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318)
	strip-nondeterminism --timestamp "$SOURCE_DATE_EPOCH" "target/system-rules-$pkgver.jar"
}

check() {
	cd "$pkgname"
	mvn test
}

package() {
	cd "$pkgname"
	install -Dm644 "target/system-rules-$pkgver.jar" -t "$pkgdir/usr/share/java/junit-system-rules"
	ln -s "system-rules-$pkgver.jar" "$pkgdir/usr/share/java/junit-system-rules/system-rules.jar"
}
