post_install() {
  cat << EOF

To make use of SLIME, add the following lines to your
Emacs configuration file:

(setq inferior-lisp-program "/path/to/lisp-executable")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/slime/")
(require 'slime)
(slime-setup)

Then run 'M-x slime' from within Emacs.

EOF
}

post_remove() {
cat << EOF

You may want to remove SLIME related lines from your
Emacs configuration.

EOF
}
