post_install() {
	[ -x usr/bin/update-desktop-database ] && update-desktop-database -q
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	glib-compile-schemas usr/share/glib-2.0/schemas
}

post_upgrade() {
	post_install $1
}

post_remove() {
	[ -x usr/bin/update-desktop-database ] && update-desktop-database -q
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	glib-compile-schemas usr/share/glib-2.0/schemas
}
