post_install() {
    cat << '__EOF__'
warning: XSI compliance is not 100% complete, not all tools are packaged.
         - The SCCS development tools are not available, but may be obtained
           from the AUR in the event you believe anyone still uses it.
         - The cflow package can likewise be obtained from the AUR.
         - A cxref package may need to be created, if there are interested
           parties.
__EOF__
}
