pre_install() {
  /bin/true
}

post_install() {
  mkdir -p /var/db/sshguard
  echo "-- You should add chain to your firewall:"
  echo "--   iptables -N sshguard"
  echo "--   iptables -A INPUT -p tcp --dport 22 -j sshguard"
  echo "-- For more information, see http://www.sshguard.net/doc/"
  /bin/true
}

pre_upgrade() {
  /bin/true
}

post_upgrade() {
  /bin/true
}

pre_remove() {
  /bin/true
}

post_remove() {
  /bin/true
}
