post_install() {
  update-desktop-database -q

  # add sagemath user for the daemon
  useradd -r -c 'Sage daemon' -d /var/lib/sage -s /bin/false sagemath
}

post_upgrade() {
  post_install $1
  echo "There is now a user session unit included to run a sage notebook as your user."
  echo "The wiki includes a guide on starting systemd user sessions"
}

post_remove() {
  # remove the sagemath daemon user
  userdel sagemath
}
