#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/nbd

PIDFILE="/var/run/nbd-server.$NBD_PORT.pid"
PID=`cat $PIDFILE 2>/dev/null`
case "$1" in
  start)
    stat_busy "Starting Network Block Device Server"
    if [ "$PID" = "" ]; then 
       /usr/bin/nbd-server $NBD_PORT $NBD_DEV $NBD_ARGS 
    fi
    if [ "$PID" != "" -o $? -gt 0 ]; then
      stat_fail
    else
      add_daemon nbd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Network Block Device Server"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    rm -f $PIDFILE
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon nbd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
