#!/bin/sh

systemctl start --user keybase.service kbfs.service
systemctl start --user keybase.gui.service

# executing the application when it is already running will bring it to the
# foreground
if [ "$KEYBASE_START_UI" != 'hideWindow' ]; then
    exec electron /usr/share/keybase-app/ "$@"
fi
