#!/bin/sh

keybase ctl init
systemctl start --user keybase kbfs

if [ $# -gt 0 ] || systemctl --user is-active --quiet keybase.gui; then
    exec electron /usr/share/keybase-app "$@"
else
    systemctl --user import-environment KEYBASE_AUTOSTART
    exec systemctl start --user --wait keybase.gui
fi
