#!/bin/bash

# source application-specific settings
GKRELLMD_ARGS='-d'

. /etc/rc.conf
. /etc/rc.d/functions

PID=$(pidof -o %PPID /usr/bin/gkrellmd)
case "$1" in
  start)
    stat_busy "Starting GKrellM Daemon"
    [ -z "$PID" ] && /usr/bin/gkrellmd ${GKRELLMD_ARGS}
    PID=$(pidof -o %PPID /usr/bin/gkrellmd)
    if [ -z "$PID" ]; then
      stat_fail
    else
      add_daemon gkrellmd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping GKrellM Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon gkrellmd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
