post_install() {
if [ -x /usr/bin/gtk-update-icon-cache ]; then
   echo Updating icon cache...
   /usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/hicolor
fi
if [ -x /usr/bin/update-desktop-database ]; then
   echo Updating desktop database..
   /usr/bin/update-desktop-database /usr/share/applications
fi
update-mime-database usr/share/mime
}

post_upgrade() {
post_install
}

post_remove() {
post_install
}