.TH "SPEC2ARCH.CONF" "5" "01 July 2008"
.SH "NAME" 
spec2arch.conf.conf \- Configuration file for \fBspec2arch\fR, which creates
ArchLinux PKGBUILD files from RPM spec files
.SH "DESCRIPTION" 
.PP 
This manual page documents the options that can be set in the spec2arch.conf
configuration file. For a description of what spec2arch does, see the
spec2arch(8) manpage.

.SH "SETTINGS" 
.PP 
The syntax of options is OPTION=value - Bash syntax, since it will be sourced
by the pkgmake executable, which is written in Bash script.

.PP
The following settings are available in spec2arch.conf: 

.IP "\fBSRC_BASEURL\fP" 10
Here you can define a base URL where the source is available for download.
The string from this setting will be put in front of the source file name
defined in the RPM .spec file.

.IP "\fBUSE_WARNING\fP" 10
Since the automatic creation of the PKGBUILD file may result in invalid
settings and thus need a review, spec2arch can add a warning hint to that
fact. You should only ommit it if you are really sure the created PKGBUILD
file will be 100% correct. Valid settings are: 0 (no warning) or 1 (default
- place a warning).

.IP "\fBOVERWRITE_TARGET\fP" 10
What shall be done if the target PKGBUILD file specified on the command line
does already exist - shall it be overwritten without a warning (1), or shall
spec2arch better exit with a warning (0 - default)?

.IP "\fBBUILD_REPLACE\fR / \fBBUILD_REPLACED\fR"
Replacements to be made in the build() section. The RPM .spec file has some
pre-defined variables and conditional scripting which we may need to replace.
Since the replace is done using "sed", all statements need to comply to regexp
(i.e. escape certain characters).

For the replace, we set up two arrays which need to correspond to each other:
BUILD_REPLACE holds the strings to be replaced, BUILD_REPLACED the replacement.
There are no defaults.

.IP "\fBBUILD_REMOVE\fR"
Similiar to above explained \fIBUILD_REPLACE\fR, this is an array of regular
expressions describing lines to be completely removed (or, better said:
ignored) from the RPM .spec file - i.e. they will not be considered for the
PKGBUILD file at all.

.IP "\fBDO_BUILD_REPLACE\fR"
Whether we should apply the changes defined by \fIBUILD_REPLACE\fR,
\fIBUILD_REPLACED\fR and \fIBUILD_REMOVE\fR (1) or not (0 - default).

.IP "\fBEDIT_PKGBUILD\fR"
Shall we invoke the editor after creating the PKGBUILD files to apply manual
changes (1, default) or not (0)? Unless you are sure the resulting file will
be fine (or adjustments should be done later), you should manually
post-process the created PKGBUILD file to make sure it is OK.

.IP "\fBEDITOR\fR"
Which editor shall be used (to edit the PKGBUILD file if EDIT_PKGBUILD=1)? By
default, spec2arch will use the editor defined by the system variable $EDITOR.

.IP "\fBUSE_NAMCAP\fR"
If namcap.py is found in the $PATH, shall it be used to verify the generated
PKGBUILD file (1 - default) or not (0)? It is recommended to use this tool
to detect possible problems.

.SH "SEE ALSO" 
.PP 
spec2arch(8)

.SH "AUTHOR" 
.PP 
This manual page was written by Andreas Itzchak Rehberg (devel@izzysoft.de),
the author of the program. Permission is granted to copy, distribute and/or
modify this document under the terms of the GNU General Public License,
Version 2.

More information may be found on the authors website, http://www.izzysoft.de/
 
