post_install() {
update-mime-database usr/share/mime > /dev/null

cat << EOF
Note:
==> In case you experience access permission error for the attached GPS device,
==> see http://wiki.openstreetmap.org/wiki/USB_Garmin_on_GNU/Linux for more details.
==> Disable garmin_gps module in /etc/rc.conf and see included example udev rule.
EOF
}

post_remove() {
update-mime-database usr/share/mime > /dev/null
}
