#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=$(ps aux | grep -v grep | grep /usr/sbin/mfscgiserv | awk '{print $2}')
case "$1" in
  start)
    stat_busy "Starting MooseFS CGI Web Frontend Daemon"
    [ -z "$PID" ] && /usr/sbin/mfscgiserv &>/dev/null
    if [ $? = 0 ]; then
      add_daemon mfscgiserv
      stat_done
    else
      stat_fail
      exit 1
    fi
    ;;
  stop)
    stat_busy "Stopping MooseFS CGI Web Frontend Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon mfscgiserv
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
