#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/bin/mfschunkserver`
case "$1" in
  start)
    stat_busy "Starting MooseFS Chunkserver Daemon"
    if [ -z "$PID" ]; then 
       /usr/bin/mfschunkserver start
    fi
    if [ ! -z "$PID" -o $? -gt 0 ]; then
      stat_fail
    else
      PID=`pidof -o %PPID /usr/bin/mfschunkserver`
      echo $PID > /var/run/mfsmetalogger.pid
      add_daemon mfschunkserver
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping MooseFS Chunkserver Daemon"
    [ ! -z "$PID" ]  && /usr/bin/mfschunkserver stop &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon mfschunkserver
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
