pkgname=gnome-sound-recorder

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  if [ "$(vercmp 3.4.0-2 "$2")" -eq 1 ]; then
    usr/sbin/gconfpkg --uninstall gnome-media
  else
    usr/sbin/gconfpkg --uninstall ${pkgname}
  fi
}

post_remove() {
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}
