post_install() {
   echo "    dpkg installs Debian package manager for you."
   echo "    It is useful for those who wants to create/modify DEB files."
   echo "    But do not use dpkg to install Debian packages at your ArchLinux machine."
   echo "    It will break your system!"
   echo "    You will need to go back to Arch wiki and read the installation guide again."
   echo "    You've been warned!"
}
