#!/bin/bash

# arg 1:  the new package version
post_install() {
  systemd-sysusers virtualbox-guest-utils.conf
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install "$1"
  # rename /etc/rc.d/vboxservice
  if [[ $(vercmp "$2" 4.1.18-3) < 0 ]]; then
    echo "==> rc.d vbox-service script was renamed to vboxservice."
  fi
  # fix gid of vboxsf
  if [[ $(vercmp "$2" 4.1.18-4) < 0 ]]; then
    groupmod -g 109 vboxsf
  fi
  return 0
}

# vim:set ts=2 sw=2 ft=sh et:
