#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/mfsmetalogger`
case "$1" in
  start)
    stat_busy "Starting MooseFS Metalogger Daemon"
    if [ -z "$PID" ]; then 
       /usr/sbin/mfsmetalogger start
    fi
    if [ ! -z "$PID" -o $? -gt 0 ]; then
      stat_fail
    else
      PID=`pidof -o %PPID /usr/sbin/mfsmetalogger`
      echo $PID > /var/run/mfsmetalogger.pid
      add_daemon mfsmetalogger
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping MooseFS Metalogger Daemon"
    [ ! -z "$PID" ]  && /usr/sbin/mfsmetalogger stop &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon mfsmetalogger
      rm /var/run/mfsmetalogger.pid
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
