post_upgrade() {
        echo " >>> Since 1.2.1-2 several changes has been made in package."
        echo "      - *.conf files has been moved to /etc/nginx"
        echo "      - /etc/conf.d/nginx has been removed"
        echo "        Main configuration files is set to /etc/nginx/nginx.conf"
        echo "      - access.log and error.log can be found in /var/log/nginx at default" 
        echo "      - bundled *.html files has been moved to /usr/share/nginx/html"
        echo "      - /etc/nginx/{html,logs} symbolic links and *.default files have been removed"
}
