#!/bin/bash

LIBDIR="@LIBDIR@"

if [[ -e "$LIBDIR/libv4l/v4l2convert.so" ]]; then
	export LD_PRELOAD="$LIBDIR/libv4l/v4l2convert.so"
fi

export LD_PRELOAD="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/share/skype/lib/libQtWebKit.so.4"

exec "$LIBDIR/skype/skype" "$@"
