#!/bin/sh
if [ "$(ulimit -n)" != "unlimited" ] ; then
    ulimit -n 16384 > /dev/null 2>&1 || \
    ulimit -n 8192 > /dev/null 2>&1 || \
    ulimit -n 4096 > /dev/null 2>&1 || \
    ulimit -n 2048 > /dev/null 2>&1 || \
    ulimit -n 1024 > /dev/null 2>&1 || \
    ulimit -n 512 > /dev/null 2>&1
fi

METEORDIR=/usr/lib/meteor
export NODE_PATH=$METEORDIR/lib/node_modules
exec /usr/bin/node $METEORDIR/app/meteor/meteor.js "$@"
