post_install() {
  if ! getent passwd kibana &>/dev/null; then
    groupadd -r -g 206 kibana &>/dev/null
    useradd -r -u 206 -g kibana -d /var/lib/kibana -s /bin/nologin -c 'kibana user' kibana &>/dev/null
    passwd -l kibana &>/dev/null
  fi
}

post_upgrade() {
  post_install $1
  if (( $(vercmp $2 5.5.0-2) <= 0 )); then
    chown -R 206:206 /usr/share/kibana/{optimize,data}
    chmod -R o-w,g-w /usr/share/kibana/{optimize,data}
  fi
}

# vim: ts=2 sw=2 et:
