post_install() {
    echo "Please use systemd units to start/stop goagent:"
    echo "sudo systemctl start/stop goagent"
    
    #cd /opt/goagent/local
    #python2 -c 'from proxy import CertUtil; CertUtil.check_ca()'
    chown -R nobody:daemon /usr/share/goagent/local
}

post_upgrade() {
    post_install
}

pre_upgrade() {
    rm -rf /opt/goagent/local/certs
    rm -rf /usr/share/goagent/local/certs
}

pre_remove() {
    rm -rf /opt/goagent/local/certs
    rm -rf /usr/share/goagent/local/certs
}
