post_upgrade() {
  cat << EOF
---[ NOTE ]------------------------------------------------------------------
 Processing does not really support OpenJDK, only Java from Sun and Oracle.
 See: https://github.com/processing/processing/wiki/Supported-Platforms#linux
 If you encounter any issues with this package, please file bug reports with
 Processing and/or OpenJDK until Processing can officially support OpenJDK.
-----------------------------------------------------------------------------
EOF
}

post_install() {
  post_upgrade
}
