post_install() {
   echo "    rpm-tools installs RedHat package manager for you."
   echo "    It is useful for those who wants to create/modify RPM files."
   echo "    But do not use rpm-tools to install RedHat packages at your ArchLinux machine."
   echo "    It will break your system!"
   echo "    You will need to go back to Arch wiki and read the installation guide again."
   echo "    You've been warned!"
}
