--- Makefile	2007-11-19 08:24:56.000000000 +0100
+++ Makefile.new	2007-11-20 11:23:31.000000000 +0100
@@ -9,7 +9,7 @@ BINPATH = /usr/bin
 SCRPATH = /etc/atop
 LOGPATH = /var/log/atop
 MANPATH = /usr/share/man/man1
-INIPATH = /etc/rc.d/init.d
+INIPATH = /etc/rc.d
 CRNPATH = /etc/cron.d
 ROTPATH = /etc/logrotate.d
 
