post_upgrade() {

    [[ $(vercmp $2 0.7.1) -ge 0 ]] && return

    echo "---------------------------------------------------------------------
    stone-soup saves have moved to ~/.stone-soup.
    if you want to keep your old saves, move /var/games/stone-soup to
    ~/.stone-soup with your user as owner.

    stone-soup now also includes the tiles version (crawl-tiles)
---------------------------------------------------------------------"
}
