post_install() {
    echo "Since 3.1.2-2, /etc/goagent becomes user configuration for goagent. Put any customization there, not the default settings. For details, please refer to wiki: https://wiki.archlinux.org/index.php?title=GoAgent_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)"
    
    #cd /opt/goagent/local
    #python2 -c 'from proxy import CertUtil; CertUtil.check_ca()'
    chown -R nobody:daemon /usr/share/goagent/local
}

post_upgrade() {
    post_install
}

pre_upgrade() {
    # Disable certs cleaning until some more issue detected
    #rm -rf /usr/share/goagent/local/certs
    :
}

pre_remove() {
    rm -rf /usr/share/goagent/local/certs
}
