#!/bin/sh

__bootstrap() {
    cd ~/.factor
    ln -sf /usr/share/factor/boot.image .
    f-bin -i=boot.image
    mv f-bin.image factor.image
    rm boot.image
}

[ ! -d ~/.factor ] && mkdir -p ~/.factor
[ ! -h ~/.factor/libs ] && ln -sf /usr/lib/factor/* ~/.factor/

bootmtime=$(stat -c="%Y" /usr/share/factor/boot.image)

if [ -f ~/.factor/factor.image ]; then
    imagemtime=$(stat -c="%Y" ~/.factor/factor.image)
    if [ -f ~/.factor-boot-rc ]; then
        brcmtime=$(stat -c="%Y" ~/.factor-boot-rc)
        (  [ ${brcmtime#=} -gt ${imagemtime#=} ] \
        || [ ${bootmtime#=} -gt ${imagemtime#=} ] \
        ) && __bootstrap
    else
        [ ${bootmtime#=} -gt ${imagemtime#=} ] && __bootstrap
    fi
else
    __bootstrap
fi

/usr/bin/f-bin -i=$HOME/.factor/factor.image $*
