#!/bin/bash
source /usr/share/GNUstep/Makefiles/GNUstep.sh
if [ ! -d ~/.Oolite/AddOns ]; then
    mkdir -p ~/.Oolite/AddOns
fi
if [ ! -d ~/~/GNUstep/Library/ApplicationSupport/Oolite/ManagedAddOns ]; then
    mkdir -p ~/GNUstep/Library/ApplicationSupport/Oolite/ManagedAddOns
fi
/usr/share/oolite/oolite "$@"
