.TH KEEPASS 1 "Mar 19, 2011"
.SH NAME
keepass \- password manager
.SH SYNOPSIS
.B keepass
.SH DESCRIPTION
\fBKeePass\fP is a free/open-source password manager or safe which helps you to manage your passwords in a secure way. You can put all your passwords in one database, which is locked with one master key or a key file. So you only have to remember one single master password to unlock the whole database. The databases are encrypted using AES-256.
.SH OPTIONS
.TP
\fB\-\-auto-type\fP
invokes global auto-type
.TP
\fB\-\-lock-all\fP
lock databases of all KeePass instances
.TP
\fB\-\-unlock-all\fP
unlock databases of all KeePass instances
.TP
\fB\-\-exit-all\fP
exit all KeePass instances
.SH AUTHOR
This manual page was written by Julian Taylor <jtaylor.debian@googlemail.com>,
for the Debian project (but may be used by others).
