# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  if [ "$(vercmp "$2" 21.0.0)" -le 0 ]; then
    printf "WARNING: Major changes introduced to package!\n"
    printf "         The application is now run as its own user - nextcloud.\n"
    printf "         Default directories for runtime, state and log files are provided.\n"
    printf "         The configuration file is now in /etc/webapps/nextcloud/config.php.\n"
    printf "         A convenience wrapper around occ is provided in /usr/bin/occ.\n"
  fi
}
