post_install() {
  # Update LaTeX db to point to SageTeX
  if [ -f /usr/bin/texhash ]; then
    /usr/bin/texhash /usr/share/texmf
  else
    echo 'Warning: could not find /usr/bin/texhash'
    echo 'SageTeX has been installed but you need to run:'
    echo '# texhash /usr/share/texmf'
    echo 'So that LaTeX will be able to find it.'
  fi
}

post_remove() {
  if [ -f /usr/bin/texhash ]; then
    /usr/bin/texhash /usr/share/texmf
  fi
}