#!/bin/bash

# arg 1:  the new package version
post_install() {
	if [[ ! -e /etc/synapse/homeserver.yaml ]]; then
		cat <<-EOF
		==> A synapse configuration file needs to be generated before you can
		    start synapse, and you should make sure that it's readable by the
		    synapse user.

		    cd /var/lib/synapse
		    sudo -u synapse python -m synapse.app.homeserver \\
		      --server-name my.domain.name \\
		      --config-path /etc/synapse/homeserver.yaml \\
		      --generate-config \\
		      --report-stats=yes

		    N.B.: The default synapse config enables the webclient feature.
		          You need to either disable it, install the syweb python package
		          from matrix-angular-sdk, or set 'web_client_location' to a path
		          to make synapse not try to serve it using syweb.
		EOF
		install -dm700 -o 198 -g 198 /var/lib/synapse
	fi
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	if [[ "$(vercmp "$2" 1.4.0-2)" -lt 0 ]]; then
		cat <<-EOF
		==> Upstream email templates are no longer available in /var/lib/synapse/res/templates.

		    If you want to customize the templates, you can copy the default ones from
		    /usr/lib/python3.x/site-packages/synapse/res/templates/
		EOF
	fi
}
