#!/bin/sh

checkgroups() {
  getent group lock >/dev/null || groupadd -g 54 lock
}

post_install() {
  checkgroups

  [ -f etc/machine-id ] || systemd-machine-id-setup

  echo "systemd has been installed to /bin/systemd. Please ensure you append"
  echo "init=/bin/systemd to your kernel command line in your bootloader."
}

post_upgrade() {
  checkgroups

  [ -f etc/machine-id ] || systemd-machine-id-setup
  systemctl daemon-reexec >/dev/null || :
}

pre_remove() {
  rm -f /etc/systemd/system/default.target
}

post_remove() {
  getent group lock >/dev/null && groupdel lock
}

# vim:set ts=2 sw=2 et:
