INFO_DIR=usr/share/info

INFO_FILES=(ada-mode auth autotype bovine calc ccmode cl dbus dired-x
ebrowse ede ediff edt efaq eieio eintr elisp emacs-gnutls emacs-mime
emacs epa erc ert eshell eudc eww flymake forms gnus htmlfontify idlwave
ido mairix-el message mh-e newsticker nxml-mode octave-mode org pcl-cvs
pgg rcirc reftex remember sasl sc semantic ses sieve smtpmail speedbar
srecode todo-mode tramp url vip viper widget wisent woman)

post_install() {
  [[ -x usr/bin/install-info ]] || return 0
  for f in ${INFO_FILES[@]}; do
    install-info ${INFO_DIR}/$f.info.gz ${INFO_DIR}/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [[ -x usr/bin/install-info ]] || return 0
  for f in ${INFO_FILES[@]}; do
    install-info --delete ${INFO_DIR}/$f.info.gz ${INFO_DIR}/dir 2> /dev/null
  done
}
