EXTRAMODULES='extramodules-3.0-lts'

post_install() {
/bin/cat << EOF
===> You must load vboxdrv module before starting VirtualBox:
===> # modprobe vboxdrv
EOF
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

post_upgrade() {
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
    echo 'In order to use the new version, reload all virtualbox modules manually.'
}

post_remove() {
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
}
