--- scite/gtk/makefile.orig	2010-07-01 02:33:19.166295432 -0500
+++ scite/gtk/makefile	2010-07-01 02:34:37.140037787 -0500
@@ -46,7 +46,7 @@
 ifdef DEBUG
 CXXTFLAGS=-DDEBUG -g $(CXXBASEFLAGS)
 else
-CXXTFLAGS=-DNDEBUG -Os $(CXXBASEFLAGS)
+CXXTFLAGS=-DNDEBUG #ARCHCXXFLAGS# $(CXXBASEFLAGS)
 endif
 
 ifndef NO_LUA
--- scintilla/gtk/makefile.orig	2010-07-01 02:35:33.288735024 -0500
+++ scintilla/gtk/makefile	2010-07-01 02:36:35.406694846 -0500
@@ -29,7 +29,7 @@
 vpath %.cxx ../src
 
 INCLUDEDIRS=-I ../include -I ../src
-CXXBASEFLAGS=-Wall -Wno-missing-braces -Wno-char-subscripts -pedantic -DGTK -DSCI_LEXER $(INCLUDEDIRS)
+CXXBASEFLAGS=-Wall -Wno-missing-braces -Wno-char-subscripts -pedantic #ARCHCXXFLAGS# -DGTK -DSCI_LEXER $(INCLUDEDIRS)
 
 ifdef NOTHREADS
 THREADFLAGS=-DG_THREADS_IMPL_NONE
@@ -40,7 +40,7 @@
 ifdef DEBUG
 CXXFLAGS=-DDEBUG -g $(CXXBASEFLAGS) $(THREADFLAGS)
 else
-CXXFLAGS=-DNDEBUG -Os $(CXXBASEFLAGS) $(THREADFLAGS)
+CXXFLAGS=-DNDEBUG $(CXXBASEFLAGS) $(THREADFLAGS)
 endif
 
 CONFIGFLAGS:=$(shell pkg-config --cflags gtk+-2.0)
