--- tools/Makefile.in
+++ tools/Makefile.in
@@ -506,7 +506,7 @@ info: info-am
 
 info-am:
 
-install-data-am: install-confDATA install-data-local \
+install-data-am: install-confDATA \
 	install-dist_bashcompDATA install-examplesDATA
 
 install-dvi: install-dvi-am
