--- tools/Makefile.in	2010-03-31 04:45:09.000000000 -0500
+++ tools/Makefile.in	2010-04-11 17:17:41.000000000 -0500
@@ -334,8 +334,7 @@
 
 info-am:
 
-install-data-am: install-confDATA install-data-local \
-	install-examplesDATA
+install-data-am: install-confDATA install-examplesDATA
 
 install-dvi: install-dvi-am
 
