post_install() {
  glib-compile-schemas usr/share/glib-2.0/schemas
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-desktop-database -q
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  glib-compile-schemas usr/share/glib-2.0/schemas
}

post_remove() {
  update-desktop-database -q
  gtk-update-icon-cache -q -f -t usr/share/icons/hicolor
}
