#!/bin/bash

CONF=/etc/conf.d/openntpd

. /etc/rc.conf
. /etc/rc.d/functions
[[ -f $CONF ]] && . "$CONF"

PID=$(pidof -o %PPID /usr/sbin/ntpd)
case $1 in
  start)
    stat_busy "Starting OpenNTPD"
    [[ -d /run/openntpd ]] || mkdir /run/openntpd
    if [[ $PID ]] || ! /usr/sbin/ntpd $PARAMS; then
      stat_fail
    else
      pidof -o %PPID /usr/sbin/ntpd >/run/openntpd.pid
      add_daemon openntpd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping OpenNTPD"
    if [[ -z $PID ]] || ! kill $PID &>/dev/null; then
      stat_fail
    else
      rm_daemon openntpd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
