post_install() {
  getent group ntp &>/dev/null || groupadd -g 87 ntp >/dev/null
  getent passwd ntp &>/dev/null || useradd -u 87 -g ntp -d /var/lib/ntp -c 'Network Time Protocol' -s /bin/false ntp >/dev/null

  systemd-tmpfiles --create openntpd.conf
  true
}

post_remove() {
  getent passwd ntp &>/dev/null && userdel ntp >/dev/null
  getent group ntp &>/dev/null && groupdel ntp >/dev/null
  true
}

# vim: ts=2 sw=2 et ft=sh
