post_upgrade() {
  # Show warning for users of the old package from AUR
  if (( $(vercmp $2 '22.02.122-5') < 0 )); then
    echo "WARNING: The 'plymouth-encrypt' and 'sd-plymouth' hooks are no longer exist in the package. You should replace them with 'encrypt' and 'plymouth' hooks in your 'mkinitcpio.conf'. The 'lxdm-plymouth.service', 'lightdm-plymouth.service' and 'sddm-plymouth.service' systemd service files are no longer exist in the package. You should enable 'lxdm.service', 'lightdm.service' or 'sddm.service' instead."
  fi
}
