# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  if (( "$(vercmp "$2" '0.17.0-1')" < 0 )); then
    printf "WARNING: Major config and functionality changes. A restart (not reload) of qtile is required.\n"
  fi
  if (( "$(vercmp "$2" '0.18.0-1')" < 0 )); then
    printf "WARNING: Major config changes. Make sure to read /usr/share/doc/qtile/CHANGELOG.\n"
  fi
}
