post_install() {
  echo ">> Place 'vhba' in MODULES= in /etc/rc.conf to enable vhba on system boot."
  echo ">> This module needs to be recompiled for every kernel version upgrade."
  EXTRAMODULES='extramodules-3.1-ARCH'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

post_upgrade() {
  post_install
}

post_remove() {
  EXTRAMODULES='extramodules-3.1-ARCH'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

