post_install() {
    groupadd osecgroup
    useradd -G osecgroup -d /var/lib/osec osec
    chown -R osec.osecgroup /var/lib/osec
    echo "-- Use osec -D /var/lib/osec -u osec -g osecgroup -f /etc/osec/dirs.conf | osec_reporter"
}

post_upgrade() {
    chown -R osec.osecgroup /var/lib/osec
    echo "-- Use osec -D /var/lib/osec -u osec -g osecgroup -f /etc/osec/dirs.conf | osec_reporter"
}

post_remove() {
    userdel osec
    groupdel osecgroup
}
