post_install() {
  echo ">>>"
  echo ">>> To complete the installation you should edit /etc/php/php.ini."
  echo ">>> - Add / to the open_basedir list or comment this variable out."
  echo ">>> - Enable zip.so"
  echo ">>>"
  echo ">>> EXAMPLE:"
  echo ">>> ; open_basedir = /srv/http/:/home/:/tmp/:/usr/share/pear/:/"
  echo ">>> extension=zip.so"
  echo ">>>"
  echo ">>> To enable the GUI make sure you install php-gtk from aur"
}
