post_install() {
  echo ">>>"
  echo ">>> To complete the installation you should edit /etc/php/php.ini."
  echo ">>> Add / to the open_basedir list."
  echo ">>> Enable zip.so and json.so."
  echo ">>>"
  echo ">>> EXAMPLE:"
  echo ">>> open_basedir = /srv/http/:/home/:/tmp/:/usr/share/pear/:/"
  echo ">>> extension=zip.so"
  echo ">>> extension=json.so"
  echo ">>>"
  echo ">>> To enable the GUI make sure you install php-gtk from aur"
}
