#!/bin/bash

die () {
        local ret=$1; 
        local warning="$2"; shift 2
        warn "${warning:-Unknown error}" "$@"
        quit ${ret:-1}
}

warn () {
        local message="$1"; shift
        printf "$message" "$@" 1>&2
}

quit () {
        exit ${1:-0}
}

msg  () {
        local message="$1"
        shift
        printf "$message" $@
}

# vim: set ts=8 et:
