post_install() {
	cat <<EOF
To allow members of the wheel group to run commands as other users,
create the file /etc/doas.conf with the following content:

	permit :wheel

Refer to doas(1) and doas.conf(5) for more information.

An important notice from README.md:

	The persist feature is disabled by default [....] This feature
	is new and potentially dangerous, in the original doas, a
	kernel API is used to set and clear timeouts. This API is
	openbsd specific and no similar API is available on other
	operating systems.

	As a workaround, the persist feature is implemented using
	timestamp files similar to sudo.
EOF
}
