KERNEL_VERSION='3.0-ARCH'

post_install() {
  cat << EOM

===> virtualbox-archlinux-modules post-install message:
===>
===> You may want to load vboxguest, vboxsf and vboxvideo
===>
===> To load them automatically, add them
===> to the MODULES array in /etc/rc.conf.

EOM

  depmod -v $KERNEL_VERSION >/dev/null 2>&1
}

post_remove() {
  depmod -v $KERNEL_VERSION >/dev/null 2>&1
}

post_upgrade() {
  depmod -v $KERNEL_VERSION >/dev/null 2>&1
}
