post_install() {
    EXTRAMODULES='extramodules-3.5-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    echo 'In order to use the catalyst module, reboot the system.'
}

post_upgrade() {
    EXTRAMODULES='extramodules-3.5-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='extramodules-3.5-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

