KERNEL_VERSION='2.6.31-ARCH'

post_install() {
  cat << EOM

===> virtualbox-modules post-install message:
===>
===> You must load vboxdrv module before starting VirtualBox:
===> # modprobe vboxdrv
===> 
===> Yout must load vboxnetflt for Host Interface Networking:
===> # modprobe vboxnetflt
===>
===> Yout must load vboxnetadp for Host-Only networking:
===> # modprobe vboxnetadp
===>
===> To load it automatically, add vboxdrv module
===> to the MODULES array in /etc/rc.conf.

EOM
    getent group vboxusers >> /dev/null || usr/sbin/groupadd -g 108 vboxusers
    depmod -v $KERNEL_VERSION >/dev/null 2>&1
}

post_remove() {
    groupdel vboxusers >/dev/null 2>&1 || true
    depmod -v $KERNEL_VERSION >/dev/null 2>&1
}

post_upgrade() {
    getent group vboxusers >> /dev/null || usr/sbin/groupadd -g 108 vboxusers
    depmod -v $KERNEL_VERSION >/dev/null 2>&1
}
