#!/bin/bash

if [ -e "/etc/rc.d/sshd" ]; then
	case "$2" in
		up)
			/etc/rc.d/sshd start
		;;
		vpn-up)
			/etc/rc.d/sshd start
		;;
		down)
			/etc/rc.d/sshd stop
		;;
		vpn-down)
			/etc/rc.d/sshd stop
		;;
	esac
fi
