#!/bin/sh

# Keep config up to date
cp -ru /usr/share/higan ~/.config/

# Prompt for profile
profile="$(zenity --list --radiolist --title 'Please select a profile' --column '' --column '' FALSE 'accuracy' TRUE 'balanced' FALSE 'performance')"

# Launch selected profile
[[ -n $profile ]] && exec higan-$profile "$@"
