post_install() {
  groupadd -r quagga
  useradd -MNr -s /bin/false -d /run/quagga -g quagga quagga && passwd -l quagga &>/dev/null
  install -d -m 750 -o quagga -g quagga /{run,etc,var/log}/quagga
  :
}

pre_remove() {
  for d in zebra ripd ripngd bgpd ospfd ospf6d isisd; do
    /etc/rc.d/$d stop &>/dev/null
  done
  :
}

post_remove() {
  userdel quagga &>/dev/null
  groupdel quagga &>/dev/null
  rmdir /{etc,var/log}/quagga
  :
}

# vim: ft=sh ts=2 sw=2 et:
