post_install() {
  echo ">>> Enable building of open-vm-tools modules:"
  echo ">>> $ dkms add open-vm-tools/${1%-*}"
  echo ">>>"
  echo ">>> Enabling vmxnet driver in /usr/lib/modprobe.d/open-vm-tools-modules.conf"
  echo ">>> (this will disable pcnet32 driver)"
  echo ">>>"
  echo ">>> If vmxnet driver doesn't handle your NIC, you have to manually"
  echo ">>> disable loading of pcnet32 driver"
  echo ">>>"
}

post_upgrade() {
  echo ">>> Enable building of open-vm-tools modules:"
  echo ">>> $ dkms add open-vm-tools/${1%-*}"
  echo ">>>"
}

post_remove() {
  echo ">>>"
  echo ">>> Remember to un-blacklist pcnet32 driver"
  echo ">>>"
}
